// Automatically generated by isl_bindings_generator.
// LICENSE: MIT

use super::{BasicSet, Context};
use libc::uintptr_t;

/// Wraps `isl_cell`.
pub struct Cell {
    pub ptr: uintptr_t,
    pub should_free_on_drop: bool,
}

extern "C" {

    fn isl_cell_free(cell: uintptr_t) -> uintptr_t;

    fn isl_cell_get_ctx(cell: uintptr_t) -> uintptr_t;

    fn isl_cell_get_domain(cell: uintptr_t) -> uintptr_t;

}

impl Cell {
    /// Wraps `isl_cell_free`.
    pub fn free(self) -> Cell {
        let cell = self;
        let mut cell = cell;
        cell.do_not_free_on_drop();
        let cell = cell.ptr;
        let isl_rs_result = unsafe { isl_cell_free(cell) };
        let isl_rs_result = Cell { ptr: isl_rs_result,
                                   should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_cell_get_ctx`.
    pub fn get_ctx(&self) -> Context {
        let cell = self;
        let cell = cell.ptr;
        let isl_rs_result = unsafe { isl_cell_get_ctx(cell) };
        let isl_rs_result = Context { ptr: isl_rs_result,
                                      should_free_on_drop: false };
        isl_rs_result
    }

    /// Wraps `isl_cell_get_domain`.
    pub fn get_domain(&self) -> BasicSet {
        let cell = self;
        let cell = cell.ptr;
        let isl_rs_result = unsafe { isl_cell_get_domain(cell) };
        let isl_rs_result = BasicSet { ptr: isl_rs_result,
                                       should_free_on_drop: true };
        isl_rs_result
    }

    /// Does not call isl_cell_free() on being dropped. (For internal use only.)
    pub fn do_not_free_on_drop(&mut self) {
        self.should_free_on_drop = false;
    }
}

impl Drop for Cell {
    fn drop(&mut self) {
        if self.should_free_on_drop {
            unsafe {
                isl_cell_free(self.ptr);
            }
        }
    }
}
