// Automatically generated by isl_bindings_generator.
// LICENSE: MIT

use super::{Aff, ConstraintList, Context, DimType, LocalSpace, Space, Val};
use libc::uintptr_t;
use std::ffi::{CStr, CString};
use std::os::raw::c_char;

/// Wraps `isl_constraint`.
pub struct Constraint {
    pub ptr: uintptr_t,
    pub should_free_on_drop: bool,
}

extern "C" {

    fn isl_constraint_alloc_equality(ls: uintptr_t) -> uintptr_t;

    fn isl_constraint_alloc_inequality(ls: uintptr_t) -> uintptr_t;

    fn isl_constraint_cmp_last_non_zero(c1: uintptr_t, c2: uintptr_t) -> i32;

    fn isl_constraint_copy(c: uintptr_t) -> uintptr_t;

    fn isl_constraint_dim(constraint: uintptr_t, type_: i32) -> i32;

    fn isl_constraint_dump(c: uintptr_t) -> ();

    fn isl_constraint_free(c: uintptr_t) -> uintptr_t;

    fn isl_constraint_get_aff(constraint: uintptr_t) -> uintptr_t;

    fn isl_constraint_get_bound(constraint: uintptr_t, type_: i32, pos: i32) -> uintptr_t;

    fn isl_constraint_get_coefficient_val(constraint: uintptr_t, type_: i32, pos: i32)
                                          -> uintptr_t;

    fn isl_constraint_get_constant_val(constraint: uintptr_t) -> uintptr_t;

    fn isl_constraint_get_ctx(c: uintptr_t) -> uintptr_t;

    fn isl_constraint_get_dim_name(constraint: uintptr_t, type_: i32, pos: u32) -> *const c_char;

    fn isl_constraint_get_div(constraint: uintptr_t, pos: i32) -> uintptr_t;

    fn isl_constraint_get_local_space(constraint: uintptr_t) -> uintptr_t;

    fn isl_constraint_get_space(constraint: uintptr_t) -> uintptr_t;

    fn isl_constraint_involves_dims(constraint: uintptr_t, type_: i32, first: u32, n: u32) -> i32;

    fn isl_constraint_is_div_constraint(constraint: uintptr_t) -> i32;

    fn isl_constraint_is_equal(constraint1: uintptr_t, constraint2: uintptr_t) -> i32;

    fn isl_constraint_is_equality(constraint: uintptr_t) -> i32;

    fn isl_constraint_is_lower_bound(constraint: uintptr_t, type_: i32, pos: u32) -> i32;

    fn isl_constraint_is_upper_bound(constraint: uintptr_t, type_: i32, pos: u32) -> i32;

    fn isl_constraint_list_add(list: uintptr_t, el: uintptr_t) -> uintptr_t;

    fn isl_constraint_list_alloc(ctx: uintptr_t, n: i32) -> uintptr_t;

    fn isl_constraint_list_clear(list: uintptr_t) -> uintptr_t;

    fn isl_constraint_list_concat(list1: uintptr_t, list2: uintptr_t) -> uintptr_t;

    fn isl_constraint_list_copy(list: uintptr_t) -> uintptr_t;

    fn isl_constraint_list_drop(list: uintptr_t, first: u32, n: u32) -> uintptr_t;

    fn isl_constraint_list_dump(list: uintptr_t) -> ();

    fn isl_constraint_list_free(list: uintptr_t) -> uintptr_t;

    fn isl_constraint_list_from_constraint(el: uintptr_t) -> uintptr_t;

    fn isl_constraint_list_get_at(list: uintptr_t, index: i32) -> uintptr_t;

    fn isl_constraint_list_get_constraint(list: uintptr_t, index: i32) -> uintptr_t;

    fn isl_constraint_list_get_ctx(list: uintptr_t) -> uintptr_t;

    fn isl_constraint_list_insert(list: uintptr_t, pos: u32, el: uintptr_t) -> uintptr_t;

    fn isl_constraint_list_n_constraint(list: uintptr_t) -> i32;

    fn isl_constraint_list_reverse(list: uintptr_t) -> uintptr_t;

    fn isl_constraint_list_set_at(list: uintptr_t, index: i32, el: uintptr_t) -> uintptr_t;

    fn isl_constraint_list_set_constraint(list: uintptr_t, index: i32, el: uintptr_t) -> uintptr_t;

    fn isl_constraint_list_size(list: uintptr_t) -> i32;

    fn isl_constraint_list_swap(list: uintptr_t, pos1: u32, pos2: u32) -> uintptr_t;

    fn isl_constraint_list_to_str(list: uintptr_t) -> *const c_char;

    fn isl_constraint_negate(constraint: uintptr_t) -> uintptr_t;

    fn isl_constraint_plain_cmp(c1: uintptr_t, c2: uintptr_t) -> i32;

    fn isl_constraint_set_coefficient_si(constraint: uintptr_t, type_: i32, pos: i32, v: i32)
                                         -> uintptr_t;

    fn isl_constraint_set_coefficient_val(constraint: uintptr_t, type_: i32, pos: i32,
                                          v: uintptr_t)
                                          -> uintptr_t;

    fn isl_constraint_set_constant_si(constraint: uintptr_t, v: i32) -> uintptr_t;

    fn isl_constraint_set_constant_val(constraint: uintptr_t, v: uintptr_t) -> uintptr_t;

    fn isl_constraint_to_list(el: uintptr_t) -> uintptr_t;

}

impl Constraint {
    /// Wraps `isl_constraint_alloc_equality`.
    pub fn alloc_equality(ls: LocalSpace) -> Constraint {
        let mut ls = ls;
        ls.do_not_free_on_drop();
        let ls = ls.ptr;
        let isl_rs_result = unsafe { isl_constraint_alloc_equality(ls) };
        let isl_rs_result = Constraint { ptr: isl_rs_result,
                                         should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_constraint_alloc_inequality`.
    pub fn alloc_inequality(ls: LocalSpace) -> Constraint {
        let mut ls = ls;
        ls.do_not_free_on_drop();
        let ls = ls.ptr;
        let isl_rs_result = unsafe { isl_constraint_alloc_inequality(ls) };
        let isl_rs_result = Constraint { ptr: isl_rs_result,
                                         should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_constraint_cmp_last_non_zero`.
    pub fn cmp_last_non_zero(&self, c2: &Constraint) -> i32 {
        let c1 = self;
        let c1 = c1.ptr;
        let c2 = c2.ptr;
        let isl_rs_result = unsafe { isl_constraint_cmp_last_non_zero(c1, c2) };
        isl_rs_result
    }

    /// Wraps `isl_constraint_copy`.
    pub fn copy(&self) -> Constraint {
        let c = self;
        let c = c.ptr;
        let isl_rs_result = unsafe { isl_constraint_copy(c) };
        let isl_rs_result = Constraint { ptr: isl_rs_result,
                                         should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_constraint_dim`.
    pub fn dim(&self, type_: DimType) -> i32 {
        let constraint = self;
        let constraint = constraint.ptr;
        let type_ = type_.to_i32();
        let isl_rs_result = unsafe { isl_constraint_dim(constraint, type_) };
        isl_rs_result
    }

    /// Wraps `isl_constraint_dump`.
    pub fn dump(&self) -> () {
        let c = self;
        let c = c.ptr;
        let isl_rs_result = unsafe { isl_constraint_dump(c) };
        isl_rs_result
    }

    /// Wraps `isl_constraint_free`.
    pub fn free(self) -> Constraint {
        let c = self;
        let mut c = c;
        c.do_not_free_on_drop();
        let c = c.ptr;
        let isl_rs_result = unsafe { isl_constraint_free(c) };
        let isl_rs_result = Constraint { ptr: isl_rs_result,
                                         should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_constraint_get_aff`.
    pub fn get_aff(&self) -> Aff {
        let constraint = self;
        let constraint = constraint.ptr;
        let isl_rs_result = unsafe { isl_constraint_get_aff(constraint) };
        let isl_rs_result = Aff { ptr: isl_rs_result,
                                  should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_constraint_get_bound`.
    pub fn get_bound(&self, type_: DimType, pos: i32) -> Aff {
        let constraint = self;
        let constraint = constraint.ptr;
        let type_ = type_.to_i32();
        let isl_rs_result = unsafe { isl_constraint_get_bound(constraint, type_, pos) };
        let isl_rs_result = Aff { ptr: isl_rs_result,
                                  should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_constraint_get_coefficient_val`.
    pub fn get_coefficient_val(&self, type_: DimType, pos: i32) -> Val {
        let constraint = self;
        let constraint = constraint.ptr;
        let type_ = type_.to_i32();
        let isl_rs_result = unsafe { isl_constraint_get_coefficient_val(constraint, type_, pos) };
        let isl_rs_result = Val { ptr: isl_rs_result,
                                  should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_constraint_get_constant_val`.
    pub fn get_constant_val(&self) -> Val {
        let constraint = self;
        let constraint = constraint.ptr;
        let isl_rs_result = unsafe { isl_constraint_get_constant_val(constraint) };
        let isl_rs_result = Val { ptr: isl_rs_result,
                                  should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_constraint_get_ctx`.
    pub fn get_ctx(&self) -> Context {
        let c = self;
        let c = c.ptr;
        let isl_rs_result = unsafe { isl_constraint_get_ctx(c) };
        let isl_rs_result = Context { ptr: isl_rs_result,
                                      should_free_on_drop: false };
        isl_rs_result
    }

    /// Wraps `isl_constraint_get_dim_name`.
    pub fn get_dim_name(&self, type_: DimType, pos: u32) -> &str {
        let constraint = self;
        let constraint = constraint.ptr;
        let type_ = type_.to_i32();
        let isl_rs_result = unsafe { isl_constraint_get_dim_name(constraint, type_, pos) };
        let isl_rs_result = unsafe { CStr::from_ptr(isl_rs_result) };
        let isl_rs_result = isl_rs_result.to_str().unwrap();
        isl_rs_result
    }

    /// Wraps `isl_constraint_get_div`.
    pub fn get_div(&self, pos: i32) -> Aff {
        let constraint = self;
        let constraint = constraint.ptr;
        let isl_rs_result = unsafe { isl_constraint_get_div(constraint, pos) };
        let isl_rs_result = Aff { ptr: isl_rs_result,
                                  should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_constraint_get_local_space`.
    pub fn get_local_space(&self) -> LocalSpace {
        let constraint = self;
        let constraint = constraint.ptr;
        let isl_rs_result = unsafe { isl_constraint_get_local_space(constraint) };
        let isl_rs_result = LocalSpace { ptr: isl_rs_result,
                                         should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_constraint_get_space`.
    pub fn get_space(&self) -> Space {
        let constraint = self;
        let constraint = constraint.ptr;
        let isl_rs_result = unsafe { isl_constraint_get_space(constraint) };
        let isl_rs_result = Space { ptr: isl_rs_result,
                                    should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_constraint_involves_dims`.
    pub fn involves_dims(&self, type_: DimType, first: u32, n: u32) -> bool {
        let constraint = self;
        let constraint = constraint.ptr;
        let type_ = type_.to_i32();
        let isl_rs_result = unsafe { isl_constraint_involves_dims(constraint, type_, first, n) };
        let isl_rs_result = match isl_rs_result {
            0 => false,
            1 => true,
            _ => panic!("Got isl_bool = -1"),
        };
        isl_rs_result
    }

    /// Wraps `isl_constraint_is_div_constraint`.
    pub fn is_div_constraint(&self) -> bool {
        let constraint = self;
        let constraint = constraint.ptr;
        let isl_rs_result = unsafe { isl_constraint_is_div_constraint(constraint) };
        let isl_rs_result = match isl_rs_result {
            0 => false,
            1 => true,
            _ => panic!("Got isl_bool = -1"),
        };
        isl_rs_result
    }

    /// Wraps `isl_constraint_is_equal`.
    pub fn is_equal(&self, constraint2: &Constraint) -> i32 {
        let constraint1 = self;
        let constraint1 = constraint1.ptr;
        let constraint2 = constraint2.ptr;
        let isl_rs_result = unsafe { isl_constraint_is_equal(constraint1, constraint2) };
        isl_rs_result
    }

    /// Wraps `isl_constraint_is_equality`.
    pub fn is_equality(&self) -> bool {
        let constraint = self;
        let constraint = constraint.ptr;
        let isl_rs_result = unsafe { isl_constraint_is_equality(constraint) };
        let isl_rs_result = match isl_rs_result {
            0 => false,
            1 => true,
            _ => panic!("Got isl_bool = -1"),
        };
        isl_rs_result
    }

    /// Wraps `isl_constraint_is_lower_bound`.
    pub fn is_lower_bound(&self, type_: DimType, pos: u32) -> bool {
        let constraint = self;
        let constraint = constraint.ptr;
        let type_ = type_.to_i32();
        let isl_rs_result = unsafe { isl_constraint_is_lower_bound(constraint, type_, pos) };
        let isl_rs_result = match isl_rs_result {
            0 => false,
            1 => true,
            _ => panic!("Got isl_bool = -1"),
        };
        isl_rs_result
    }

    /// Wraps `isl_constraint_is_upper_bound`.
    pub fn is_upper_bound(&self, type_: DimType, pos: u32) -> bool {
        let constraint = self;
        let constraint = constraint.ptr;
        let type_ = type_.to_i32();
        let isl_rs_result = unsafe { isl_constraint_is_upper_bound(constraint, type_, pos) };
        let isl_rs_result = match isl_rs_result {
            0 => false,
            1 => true,
            _ => panic!("Got isl_bool = -1"),
        };
        isl_rs_result
    }

    /// Wraps `isl_constraint_list_add`.
    pub fn list_add(list: ConstraintList, el: Constraint) -> ConstraintList {
        let mut list = list;
        list.do_not_free_on_drop();
        let list = list.ptr;
        let mut el = el;
        el.do_not_free_on_drop();
        let el = el.ptr;
        let isl_rs_result = unsafe { isl_constraint_list_add(list, el) };
        let isl_rs_result = ConstraintList { ptr: isl_rs_result,
                                             should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_constraint_list_alloc`.
    pub fn list_alloc(ctx: &Context, n: i32) -> ConstraintList {
        let ctx = ctx.ptr;
        let isl_rs_result = unsafe { isl_constraint_list_alloc(ctx, n) };
        let isl_rs_result = ConstraintList { ptr: isl_rs_result,
                                             should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_constraint_list_clear`.
    pub fn list_clear(list: ConstraintList) -> ConstraintList {
        let mut list = list;
        list.do_not_free_on_drop();
        let list = list.ptr;
        let isl_rs_result = unsafe { isl_constraint_list_clear(list) };
        let isl_rs_result = ConstraintList { ptr: isl_rs_result,
                                             should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_constraint_list_concat`.
    pub fn list_concat(list1: ConstraintList, list2: ConstraintList) -> ConstraintList {
        let mut list1 = list1;
        list1.do_not_free_on_drop();
        let list1 = list1.ptr;
        let mut list2 = list2;
        list2.do_not_free_on_drop();
        let list2 = list2.ptr;
        let isl_rs_result = unsafe { isl_constraint_list_concat(list1, list2) };
        let isl_rs_result = ConstraintList { ptr: isl_rs_result,
                                             should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_constraint_list_copy`.
    pub fn list_copy(list: &ConstraintList) -> ConstraintList {
        let list = list.ptr;
        let isl_rs_result = unsafe { isl_constraint_list_copy(list) };
        let isl_rs_result = ConstraintList { ptr: isl_rs_result,
                                             should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_constraint_list_drop`.
    pub fn list_drop(list: ConstraintList, first: u32, n: u32) -> ConstraintList {
        let mut list = list;
        list.do_not_free_on_drop();
        let list = list.ptr;
        let isl_rs_result = unsafe { isl_constraint_list_drop(list, first, n) };
        let isl_rs_result = ConstraintList { ptr: isl_rs_result,
                                             should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_constraint_list_dump`.
    pub fn list_dump(list: &ConstraintList) -> () {
        let list = list.ptr;
        let isl_rs_result = unsafe { isl_constraint_list_dump(list) };
        isl_rs_result
    }

    /// Wraps `isl_constraint_list_free`.
    pub fn list_free(list: ConstraintList) -> ConstraintList {
        let mut list = list;
        list.do_not_free_on_drop();
        let list = list.ptr;
        let isl_rs_result = unsafe { isl_constraint_list_free(list) };
        let isl_rs_result = ConstraintList { ptr: isl_rs_result,
                                             should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_constraint_list_from_constraint`.
    pub fn list_from_constraint(self) -> ConstraintList {
        let el = self;
        let mut el = el;
        el.do_not_free_on_drop();
        let el = el.ptr;
        let isl_rs_result = unsafe { isl_constraint_list_from_constraint(el) };
        let isl_rs_result = ConstraintList { ptr: isl_rs_result,
                                             should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_constraint_list_get_at`.
    pub fn list_get_at(list: &ConstraintList, index: i32) -> Constraint {
        let list = list.ptr;
        let isl_rs_result = unsafe { isl_constraint_list_get_at(list, index) };
        let isl_rs_result = Constraint { ptr: isl_rs_result,
                                         should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_constraint_list_get_constraint`.
    pub fn list_get_constraint(list: &ConstraintList, index: i32) -> Constraint {
        let list = list.ptr;
        let isl_rs_result = unsafe { isl_constraint_list_get_constraint(list, index) };
        let isl_rs_result = Constraint { ptr: isl_rs_result,
                                         should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_constraint_list_get_ctx`.
    pub fn list_get_ctx(list: &ConstraintList) -> Context {
        let list = list.ptr;
        let isl_rs_result = unsafe { isl_constraint_list_get_ctx(list) };
        let isl_rs_result = Context { ptr: isl_rs_result,
                                      should_free_on_drop: false };
        isl_rs_result
    }

    /// Wraps `isl_constraint_list_insert`.
    pub fn list_insert(list: ConstraintList, pos: u32, el: Constraint) -> ConstraintList {
        let mut list = list;
        list.do_not_free_on_drop();
        let list = list.ptr;
        let mut el = el;
        el.do_not_free_on_drop();
        let el = el.ptr;
        let isl_rs_result = unsafe { isl_constraint_list_insert(list, pos, el) };
        let isl_rs_result = ConstraintList { ptr: isl_rs_result,
                                             should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_constraint_list_n_constraint`.
    pub fn list_n_constraint(list: &ConstraintList) -> i32 {
        let list = list.ptr;
        let isl_rs_result = unsafe { isl_constraint_list_n_constraint(list) };
        isl_rs_result
    }

    /// Wraps `isl_constraint_list_reverse`.
    pub fn list_reverse(list: ConstraintList) -> ConstraintList {
        let mut list = list;
        list.do_not_free_on_drop();
        let list = list.ptr;
        let isl_rs_result = unsafe { isl_constraint_list_reverse(list) };
        let isl_rs_result = ConstraintList { ptr: isl_rs_result,
                                             should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_constraint_list_set_at`.
    pub fn list_set_at(list: ConstraintList, index: i32, el: Constraint) -> ConstraintList {
        let mut list = list;
        list.do_not_free_on_drop();
        let list = list.ptr;
        let mut el = el;
        el.do_not_free_on_drop();
        let el = el.ptr;
        let isl_rs_result = unsafe { isl_constraint_list_set_at(list, index, el) };
        let isl_rs_result = ConstraintList { ptr: isl_rs_result,
                                             should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_constraint_list_set_constraint`.
    pub fn list_set_constraint(list: ConstraintList, index: i32, el: Constraint) -> ConstraintList {
        let mut list = list;
        list.do_not_free_on_drop();
        let list = list.ptr;
        let mut el = el;
        el.do_not_free_on_drop();
        let el = el.ptr;
        let isl_rs_result = unsafe { isl_constraint_list_set_constraint(list, index, el) };
        let isl_rs_result = ConstraintList { ptr: isl_rs_result,
                                             should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_constraint_list_size`.
    pub fn list_size(list: &ConstraintList) -> i32 {
        let list = list.ptr;
        let isl_rs_result = unsafe { isl_constraint_list_size(list) };
        isl_rs_result
    }

    /// Wraps `isl_constraint_list_swap`.
    pub fn list_swap(list: ConstraintList, pos1: u32, pos2: u32) -> ConstraintList {
        let mut list = list;
        list.do_not_free_on_drop();
        let list = list.ptr;
        let isl_rs_result = unsafe { isl_constraint_list_swap(list, pos1, pos2) };
        let isl_rs_result = ConstraintList { ptr: isl_rs_result,
                                             should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_constraint_list_to_str`.
    pub fn list_to_str(list: &ConstraintList) -> &str {
        let list = list.ptr;
        let isl_rs_result = unsafe { isl_constraint_list_to_str(list) };
        let isl_rs_result = unsafe { CStr::from_ptr(isl_rs_result) };
        let isl_rs_result = isl_rs_result.to_str().unwrap();
        isl_rs_result
    }

    /// Wraps `isl_constraint_negate`.
    pub fn negate(self) -> Constraint {
        let constraint = self;
        let mut constraint = constraint;
        constraint.do_not_free_on_drop();
        let constraint = constraint.ptr;
        let isl_rs_result = unsafe { isl_constraint_negate(constraint) };
        let isl_rs_result = Constraint { ptr: isl_rs_result,
                                         should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_constraint_plain_cmp`.
    pub fn plain_cmp(&self, c2: &Constraint) -> i32 {
        let c1 = self;
        let c1 = c1.ptr;
        let c2 = c2.ptr;
        let isl_rs_result = unsafe { isl_constraint_plain_cmp(c1, c2) };
        isl_rs_result
    }

    /// Wraps `isl_constraint_set_coefficient_si`.
    pub fn set_coefficient_si(self, type_: DimType, pos: i32, v: i32) -> Constraint {
        let constraint = self;
        let mut constraint = constraint;
        constraint.do_not_free_on_drop();
        let constraint = constraint.ptr;
        let type_ = type_.to_i32();
        let isl_rs_result = unsafe { isl_constraint_set_coefficient_si(constraint, type_, pos, v) };
        let isl_rs_result = Constraint { ptr: isl_rs_result,
                                         should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_constraint_set_coefficient_val`.
    pub fn set_coefficient_val(self, type_: DimType, pos: i32, v: Val) -> Constraint {
        let constraint = self;
        let mut constraint = constraint;
        constraint.do_not_free_on_drop();
        let constraint = constraint.ptr;
        let type_ = type_.to_i32();
        let mut v = v;
        v.do_not_free_on_drop();
        let v = v.ptr;
        let isl_rs_result =
            unsafe { isl_constraint_set_coefficient_val(constraint, type_, pos, v) };
        let isl_rs_result = Constraint { ptr: isl_rs_result,
                                         should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_constraint_set_constant_si`.
    pub fn set_constant_si(self, v: i32) -> Constraint {
        let constraint = self;
        let mut constraint = constraint;
        constraint.do_not_free_on_drop();
        let constraint = constraint.ptr;
        let isl_rs_result = unsafe { isl_constraint_set_constant_si(constraint, v) };
        let isl_rs_result = Constraint { ptr: isl_rs_result,
                                         should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_constraint_set_constant_val`.
    pub fn set_constant_val(self, v: Val) -> Constraint {
        let constraint = self;
        let mut constraint = constraint;
        constraint.do_not_free_on_drop();
        let constraint = constraint.ptr;
        let mut v = v;
        v.do_not_free_on_drop();
        let v = v.ptr;
        let isl_rs_result = unsafe { isl_constraint_set_constant_val(constraint, v) };
        let isl_rs_result = Constraint { ptr: isl_rs_result,
                                         should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_constraint_to_list`.
    pub fn to_list(self) -> ConstraintList {
        let el = self;
        let mut el = el;
        el.do_not_free_on_drop();
        let el = el.ptr;
        let isl_rs_result = unsafe { isl_constraint_to_list(el) };
        let isl_rs_result = ConstraintList { ptr: isl_rs_result,
                                             should_free_on_drop: true };
        isl_rs_result
    }

    /// Does not call isl_constraint_free() on being dropped. (For internal use
    /// only.)
    pub fn do_not_free_on_drop(&mut self) {
        self.should_free_on_drop = false;
    }
}

impl Drop for Constraint {
    fn drop(&mut self) {
        if self.should_free_on_drop {
            unsafe {
                isl_constraint_free(self.ptr);
            }
        }
    }
}
