// Automatically generated by isl_bindings_generator.
// LICENSE: MIT

use super::{Context, Error, LibISLError, MultiAff, MultiVal, Space};
use libc::uintptr_t;
use std::ffi::{CStr, CString};
use std::os::raw::c_char;

/// Wraps `isl_fixed_box`.
pub struct FixedBox {
    pub ptr: uintptr_t,
    pub should_free_on_drop: bool,
}

extern "C" {

    fn isl_fixed_box_copy(box_: uintptr_t) -> uintptr_t;

    fn isl_fixed_box_dump(box_: uintptr_t) -> ();

    fn isl_fixed_box_free(box_: uintptr_t) -> uintptr_t;

    fn isl_fixed_box_get_ctx(box_: uintptr_t) -> uintptr_t;

    fn isl_fixed_box_get_offset(box_: uintptr_t) -> uintptr_t;

    fn isl_fixed_box_get_size(box_: uintptr_t) -> uintptr_t;

    fn isl_fixed_box_get_space(box_: uintptr_t) -> uintptr_t;

    fn isl_fixed_box_is_valid(box_: uintptr_t) -> i32;

    fn isl_fixed_box_read_from_str(ctx: uintptr_t, str_: *const c_char) -> uintptr_t;

    fn isl_fixed_box_to_str(box_: uintptr_t) -> *const c_char;

}

impl FixedBox {
    /// Wraps `isl_fixed_box_copy`.
    pub fn copy(&self) -> Result<FixedBox, LibISLError> {
        let box_ = self;
        let isl_rs_ctx = box_.get_ctx();
        let box_ = box_.ptr;
        let isl_rs_result = unsafe { isl_fixed_box_copy(box_) };
        let isl_rs_result = FixedBox { ptr: isl_rs_result,
                                       should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            let err_msg = isl_rs_ctx.last_error_msg();
            isl_rs_ctx.reset_error();
            return Err(LibISLError::new(err, err_msg));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_fixed_box_dump`.
    pub fn dump(&self) -> Result<(), LibISLError> {
        let box_ = self;
        let isl_rs_ctx = box_.get_ctx();
        let box_ = box_.ptr;
        let isl_rs_result = unsafe { isl_fixed_box_dump(box_) };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            let err_msg = isl_rs_ctx.last_error_msg();
            isl_rs_ctx.reset_error();
            return Err(LibISLError::new(err, err_msg));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_fixed_box_free`.
    pub fn free(self) -> Result<FixedBox, LibISLError> {
        let box_ = self;
        let isl_rs_ctx = box_.get_ctx();
        let mut box_ = box_;
        box_.do_not_free_on_drop();
        let box_ = box_.ptr;
        let isl_rs_result = unsafe { isl_fixed_box_free(box_) };
        let isl_rs_result = FixedBox { ptr: isl_rs_result,
                                       should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            let err_msg = isl_rs_ctx.last_error_msg();
            isl_rs_ctx.reset_error();
            return Err(LibISLError::new(err, err_msg));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_fixed_box_get_ctx`.
    pub fn get_ctx(&self) -> Context {
        let box_ = self;
        let box_ = box_.ptr;
        let isl_rs_result = unsafe { isl_fixed_box_get_ctx(box_) };
        let isl_rs_result = Context { ptr: isl_rs_result,
                                      should_free_on_drop: false };
        isl_rs_result
    }

    /// Wraps `isl_fixed_box_get_offset`.
    pub fn get_offset(&self) -> Result<MultiAff, LibISLError> {
        let box_ = self;
        let isl_rs_ctx = box_.get_ctx();
        let box_ = box_.ptr;
        let isl_rs_result = unsafe { isl_fixed_box_get_offset(box_) };
        let isl_rs_result = MultiAff { ptr: isl_rs_result,
                                       should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            let err_msg = isl_rs_ctx.last_error_msg();
            isl_rs_ctx.reset_error();
            return Err(LibISLError::new(err, err_msg));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_fixed_box_get_size`.
    pub fn get_size(&self) -> Result<MultiVal, LibISLError> {
        let box_ = self;
        let isl_rs_ctx = box_.get_ctx();
        let box_ = box_.ptr;
        let isl_rs_result = unsafe { isl_fixed_box_get_size(box_) };
        let isl_rs_result = MultiVal { ptr: isl_rs_result,
                                       should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            let err_msg = isl_rs_ctx.last_error_msg();
            isl_rs_ctx.reset_error();
            return Err(LibISLError::new(err, err_msg));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_fixed_box_get_space`.
    pub fn get_space(&self) -> Result<Space, LibISLError> {
        let box_ = self;
        let isl_rs_ctx = box_.get_ctx();
        let box_ = box_.ptr;
        let isl_rs_result = unsafe { isl_fixed_box_get_space(box_) };
        let isl_rs_result = Space { ptr: isl_rs_result,
                                    should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            let err_msg = isl_rs_ctx.last_error_msg();
            isl_rs_ctx.reset_error();
            return Err(LibISLError::new(err, err_msg));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_fixed_box_is_valid`.
    pub fn is_valid(&self) -> Result<bool, LibISLError> {
        let box_ = self;
        let isl_rs_ctx = box_.get_ctx();
        let box_ = box_.ptr;
        let isl_rs_result = unsafe { isl_fixed_box_is_valid(box_) };
        let isl_rs_result = match isl_rs_result {
            0 => false,
            1 => true,
            _ => {
                return Err(LibISLError::new(Error::Unknown, "Got isl_bool = -1"));
            }
        };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            let err_msg = isl_rs_ctx.last_error_msg();
            isl_rs_ctx.reset_error();
            return Err(LibISLError::new(err, err_msg));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_fixed_box_read_from_str`.
    pub fn read_from_str(ctx: &Context, str_: &str) -> Result<FixedBox, LibISLError> {
        let isl_rs_ctx = Context { ptr: ctx.ptr,
                                   should_free_on_drop: false };
        let ctx = ctx.ptr;
        let str_ = CString::new(str_).unwrap();
        let str_ = str_.as_ptr();
        let isl_rs_result = unsafe { isl_fixed_box_read_from_str(ctx, str_) };
        let isl_rs_result = FixedBox { ptr: isl_rs_result,
                                       should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            let err_msg = isl_rs_ctx.last_error_msg();
            isl_rs_ctx.reset_error();
            return Err(LibISLError::new(err, err_msg));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_fixed_box_to_str`.
    pub fn to_str(&self) -> Result<&str, LibISLError> {
        let box_ = self;
        let isl_rs_ctx = box_.get_ctx();
        let box_ = box_.ptr;
        let isl_rs_result = unsafe { isl_fixed_box_to_str(box_) };
        let isl_rs_result = unsafe { CStr::from_ptr(isl_rs_result) };
        let isl_rs_result = isl_rs_result.to_str().unwrap();
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            let err_msg = isl_rs_ctx.last_error_msg();
            isl_rs_ctx.reset_error();
            return Err(LibISLError::new(err, err_msg));
        }
        Ok(isl_rs_result)
    }

    /// Does not call isl_fixed_box_free() on being dropped. (For internal use
    /// only.)
    pub fn do_not_free_on_drop(&mut self) {
        self.should_free_on_drop = false;
    }
}

impl Drop for FixedBox {
    fn drop(&mut self) {
        if self.should_free_on_drop {
            unsafe {
                isl_fixed_box_free(self.ptr);
            }
        }
    }
}
