// Automatically generated by isl_bindings_generator.
// LICENSE: MIT

use super::{Context, Map};
use libc::uintptr_t;

/// Wraps `isl_flow`.
pub struct Flow {
    pub ptr: uintptr_t,
    pub should_free_on_drop: bool,
}

extern "C" {

    fn isl_flow_free(deps: uintptr_t) -> uintptr_t;

    fn isl_flow_get_ctx(deps: uintptr_t) -> uintptr_t;

    fn isl_flow_get_no_source(deps: uintptr_t, must: i32) -> uintptr_t;

}

impl Flow {
    /// Wraps `isl_flow_free`.
    pub fn free(self) -> Flow {
        let deps = self;
        let mut deps = deps;
        deps.do_not_free_on_drop();
        let deps = deps.ptr;
        let isl_rs_result = unsafe { isl_flow_free(deps) };
        let isl_rs_result = Flow { ptr: isl_rs_result,
                                   should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_flow_get_ctx`.
    pub fn get_ctx(&self) -> Context {
        let deps = self;
        let deps = deps.ptr;
        let isl_rs_result = unsafe { isl_flow_get_ctx(deps) };
        let isl_rs_result = Context { ptr: isl_rs_result,
                                      should_free_on_drop: false };
        isl_rs_result
    }

    /// Wraps `isl_flow_get_no_source`.
    pub fn get_no_source(&self, must: i32) -> Map {
        let deps = self;
        let deps = deps.ptr;
        let isl_rs_result = unsafe { isl_flow_get_no_source(deps, must) };
        let isl_rs_result = Map { ptr: isl_rs_result,
                                  should_free_on_drop: true };
        isl_rs_result
    }

    /// Does not call isl_flow_free() on being dropped. (For internal use only.)
    pub fn do_not_free_on_drop(&mut self) {
        self.should_free_on_drop = false;
    }
}

impl Drop for Flow {
    fn drop(&mut self) {
        if self.should_free_on_drop {
            unsafe {
                isl_flow_free(self.ptr);
            }
        }
    }
}
