// Automatically generated by isl_bindings_generator.
// LICENSE: MIT

use crate::bindings::{Context, DimType, Space, Val};
use libc::uintptr_t;
use std::ffi::{CStr, CString};
use std::os::raw::c_char;

/// Wraps `isl_point`.
pub struct Point {
    pub ptr: uintptr_t,
}

extern "C" {

    fn isl_point_get_ctx(pnt: uintptr_t) -> uintptr_t;

    fn isl_point_get_space(pnt: uintptr_t) -> uintptr_t;

    fn isl_point_zero(space: uintptr_t) -> uintptr_t;

    fn isl_point_copy(pnt: uintptr_t) -> uintptr_t;

    fn isl_point_free(pnt: uintptr_t) -> uintptr_t;

    fn isl_point_get_coordinate_val(pnt: uintptr_t, type_: DimType, pos: i32) -> uintptr_t;

    fn isl_point_set_coordinate_val(pnt: uintptr_t, type_: DimType, pos: i32, v: uintptr_t)
                                    -> uintptr_t;

    fn isl_point_add_ui(pnt: uintptr_t, type_: DimType, pos: i32, val: u32) -> uintptr_t;

    fn isl_point_sub_ui(pnt: uintptr_t, type_: DimType, pos: i32, val: u32) -> uintptr_t;

    fn isl_point_void(space: uintptr_t) -> uintptr_t;

    fn isl_point_is_void(pnt: uintptr_t) -> i32;

    fn isl_point_to_str(pnt: uintptr_t) -> *const c_char;

    fn isl_point_dump(pnt: uintptr_t);

}

impl Point {
    /// Wraps `isl_point_get_ctx`.
    pub fn get_ctx(&self) -> Context {
        let pnt = self;
        let pnt = pnt.ptr;
        let isl_rs_result = unsafe { isl_point_get_ctx(pnt) };
        let isl_rs_result = Context { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_point_get_space`.
    pub fn get_space(&self) -> Space {
        let pnt = self;
        let pnt = pnt.ptr;
        let isl_rs_result = unsafe { isl_point_get_space(pnt) };
        let isl_rs_result = Space { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_point_zero`.
    pub fn zero(space: Space) -> Point {
        let space = space.ptr;
        let isl_rs_result = unsafe { isl_point_zero(space) };
        let isl_rs_result = Point { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_point_copy`.
    pub fn copy(&self) -> Point {
        let pnt = self;
        let pnt = pnt.ptr;
        let isl_rs_result = unsafe { isl_point_copy(pnt) };
        let isl_rs_result = Point { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_point_free`.
    pub fn free(self) -> Point {
        let pnt = self;
        let pnt = pnt.ptr;
        let isl_rs_result = unsafe { isl_point_free(pnt) };
        let isl_rs_result = Point { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_point_get_coordinate_val`.
    pub fn get_coordinate_val(&self, type_: DimType, pos: i32) -> Val {
        let pnt = self;
        let pnt = pnt.ptr;
        let isl_rs_result = unsafe { isl_point_get_coordinate_val(pnt, type_, pos) };
        let isl_rs_result = Val { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_point_set_coordinate_val`.
    pub fn set_coordinate_val(self, type_: DimType, pos: i32, v: Val) -> Point {
        let pnt = self;
        let pnt = pnt.ptr;
        let v = v.ptr;
        let isl_rs_result = unsafe { isl_point_set_coordinate_val(pnt, type_, pos, v) };
        let isl_rs_result = Point { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_point_add_ui`.
    pub fn add_ui(self, type_: DimType, pos: i32, val: u32) -> Point {
        let pnt = self;
        let pnt = pnt.ptr;
        let isl_rs_result = unsafe { isl_point_add_ui(pnt, type_, pos, val) };
        let isl_rs_result = Point { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_point_sub_ui`.
    pub fn sub_ui(self, type_: DimType, pos: i32, val: u32) -> Point {
        let pnt = self;
        let pnt = pnt.ptr;
        let isl_rs_result = unsafe { isl_point_sub_ui(pnt, type_, pos, val) };
        let isl_rs_result = Point { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_point_void`.
    pub fn void(space: Space) -> Point {
        let space = space.ptr;
        let isl_rs_result = unsafe { isl_point_void(space) };
        let isl_rs_result = Point { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_point_is_void`.
    pub fn is_void(&self) -> bool {
        let pnt = self;
        let pnt = pnt.ptr;
        let isl_rs_result = unsafe { isl_point_is_void(pnt) };
        let isl_rs_result = match isl_rs_result {
            0 => false,
            1 => true,
            _ => panic!("Got isl_bool = -1"),
        };
        isl_rs_result
    }

    /// Wraps `isl_point_to_str`.
    pub fn to_str(&self) -> &str {
        let pnt = self;
        let pnt = pnt.ptr;
        let isl_rs_result = unsafe { isl_point_to_str(pnt) };
        let isl_rs_result = unsafe { CStr::from_ptr(isl_rs_result) };
        let isl_rs_result = isl_rs_result.to_str().unwrap();
        isl_rs_result
    }

    /// Wraps `isl_point_dump`.
    pub fn dump(&self) {
        let pnt = self;
        let pnt = pnt.ptr;
        let isl_rs_result = unsafe { isl_point_dump(pnt) };
        isl_rs_result
    }
}

impl Drop for Point {
    fn drop(&mut self) {
        unsafe {
            isl_point_free(self.ptr);
        }
    }
}
