// Automatically generated by isl_bindings_generator.
// LICENSE: MIT

use crate::bindings::{Aff, Context, DimType, Id, LocalSpace, Map, Point, Set, Space, Val};
use libc::uintptr_t;
use std::ffi::{CStr, CString};
use std::os::raw::c_char;

/// Wraps `isl_pw_aff`.
pub struct PwAff {
    pub ptr: uintptr_t,
}

extern "C" {

    fn isl_pw_aff_get_ctx(pwaff: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_get_hash(pa: uintptr_t) -> u32;

    fn isl_pw_aff_get_domain_space(pwaff: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_get_space(pwaff: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_from_aff(aff: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_empty(space: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_alloc(set: uintptr_t, aff: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_zero_on_domain(ls: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_var_on_domain(ls: uintptr_t, type_: DimType, pos: u32) -> uintptr_t;

    fn isl_pw_aff_nan_on_domain_space(space: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_nan_on_domain(ls: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_val_on_domain(domain: uintptr_t, v: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_param_on_domain_id(domain: uintptr_t, id: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_get_dim_name(pa: uintptr_t, type_: DimType, pos: u32) -> *const c_char;

    fn isl_pw_aff_has_dim_id(pa: uintptr_t, type_: DimType, pos: u32) -> i32;

    fn isl_pw_aff_get_dim_id(pa: uintptr_t, type_: DimType, pos: u32) -> uintptr_t;

    fn isl_pw_aff_set_dim_id(pma: uintptr_t, type_: DimType, pos: u32, id: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_find_dim_by_name(pa: uintptr_t, type_: DimType, name: *const c_char) -> i32;

    fn isl_pw_aff_is_empty(pwaff: uintptr_t) -> i32;

    fn isl_pw_aff_involves_nan(pa: uintptr_t) -> i32;

    fn isl_pw_aff_plain_cmp(pa1: uintptr_t, pa2: uintptr_t) -> i32;

    fn isl_pw_aff_plain_is_equal(pwaff1: uintptr_t, pwaff2: uintptr_t) -> i32;

    fn isl_pw_aff_is_equal(pa1: uintptr_t, pa2: uintptr_t) -> i32;

    fn isl_pw_aff_union_min(pwaff1: uintptr_t, pwaff2: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_union_max(pwaff1: uintptr_t, pwaff2: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_union_add(pwaff1: uintptr_t, pwaff2: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_copy(pwaff: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_free(pwaff: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_dim(pwaff: uintptr_t, type_: DimType) -> i32;

    fn isl_pw_aff_involves_param_id(pa: uintptr_t, id: uintptr_t) -> i32;

    fn isl_pw_aff_involves_dims(pwaff: uintptr_t, type_: DimType, first: u32, n: u32) -> i32;

    fn isl_pw_aff_is_cst(pwaff: uintptr_t) -> i32;

    fn isl_pw_aff_insert_domain(pa: uintptr_t, domain: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_project_domain_on_params(pa: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_align_params(pwaff: uintptr_t, model: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_drop_unused_params(pa: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_has_tuple_id(pa: uintptr_t, type_: DimType) -> i32;

    fn isl_pw_aff_get_tuple_id(pa: uintptr_t, type_: DimType) -> uintptr_t;

    fn isl_pw_aff_set_tuple_id(pwaff: uintptr_t, type_: DimType, id: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_reset_tuple_id(pa: uintptr_t, type_: DimType) -> uintptr_t;

    fn isl_pw_aff_reset_user(pa: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_params(pwa: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_domain(pwaff: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_from_range(pwa: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_min(pwaff1: uintptr_t, pwaff2: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_max(pwaff1: uintptr_t, pwaff2: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_mul(pwaff1: uintptr_t, pwaff2: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_div(pa1: uintptr_t, pa2: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_add(pwaff1: uintptr_t, pwaff2: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_sub(pwaff1: uintptr_t, pwaff2: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_neg(pwaff: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_ceil(pwaff: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_floor(pwaff: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_mod_val(pa: uintptr_t, mod_: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_tdiv_q(pa1: uintptr_t, pa2: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_tdiv_r(pa1: uintptr_t, pa2: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_intersect_params(pa: uintptr_t, set: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_intersect_domain(pa: uintptr_t, set: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_intersect_domain_wrapped_domain(pa: uintptr_t, set: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_intersect_domain_wrapped_range(pa: uintptr_t, set: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_subtract_domain(pa: uintptr_t, set: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_cond(cond: uintptr_t, pwaff_true: uintptr_t, pwaff_false: uintptr_t)
                       -> uintptr_t;

    fn isl_pw_aff_add_constant_val(pa: uintptr_t, v: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_scale_val(pa: uintptr_t, v: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_scale_down_val(pa: uintptr_t, f: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_insert_dims(pwaff: uintptr_t, type_: DimType, first: u32, n: u32) -> uintptr_t;

    fn isl_pw_aff_add_dims(pwaff: uintptr_t, type_: DimType, n: u32) -> uintptr_t;

    fn isl_pw_aff_move_dims(pa: uintptr_t, dst_type: DimType, dst_pos: u32, src_type: DimType,
                            src_pos: u32, n: u32)
                            -> uintptr_t;

    fn isl_pw_aff_drop_dims(pwaff: uintptr_t, type_: DimType, first: u32, n: u32) -> uintptr_t;

    fn isl_pw_aff_coalesce(pa: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_gist(pwaff: uintptr_t, context: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_gist_params(pwaff: uintptr_t, context: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_eval(pa: uintptr_t, pnt: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_n_piece(pwaff: uintptr_t) -> i32;

    fn isl_pw_aff_isa_aff(pa: uintptr_t) -> i32;

    fn isl_pw_aff_as_aff(pa: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_as_map(pa: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_pos_set(pa: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_nonneg_set(pwaff: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_zero_set(pwaff: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_non_zero_set(pwaff: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_eq_set(pwaff1: uintptr_t, pwaff2: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_ne_set(pwaff1: uintptr_t, pwaff2: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_le_set(pwaff1: uintptr_t, pwaff2: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_lt_set(pwaff1: uintptr_t, pwaff2: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_ge_set(pwaff1: uintptr_t, pwaff2: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_gt_set(pwaff1: uintptr_t, pwaff2: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_eq_map(pa1: uintptr_t, pa2: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_le_map(pa1: uintptr_t, pa2: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_lt_map(pa1: uintptr_t, pa2: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_ge_map(pa1: uintptr_t, pa2: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_gt_map(pa1: uintptr_t, pa2: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_bind_id(pa: uintptr_t, id: uintptr_t) -> uintptr_t;

    fn isl_pw_aff_read_from_str(ctx: uintptr_t, str_: *const c_char) -> uintptr_t;

    fn isl_pw_aff_to_str(pa: uintptr_t) -> *const c_char;

    fn isl_pw_aff_dump(pwaff: uintptr_t);

}

impl PwAff {
    /// Wraps `isl_pw_aff_get_ctx`.
    pub fn get_ctx(&self) -> Context {
        let pwaff = self;
        let pwaff = pwaff.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_get_ctx(pwaff) };
        let isl_rs_result = Context { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_get_hash`.
    pub fn get_hash(&self) -> u32 {
        let pa = self;
        let pa = pa.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_get_hash(pa) };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_get_domain_space`.
    pub fn get_domain_space(&self) -> Space {
        let pwaff = self;
        let pwaff = pwaff.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_get_domain_space(pwaff) };
        let isl_rs_result = Space { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_get_space`.
    pub fn get_space(&self) -> Space {
        let pwaff = self;
        let pwaff = pwaff.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_get_space(pwaff) };
        let isl_rs_result = Space { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_from_aff`.
    pub fn from_aff(aff: Aff) -> PwAff {
        let aff = aff.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_from_aff(aff) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_empty`.
    pub fn empty(space: Space) -> PwAff {
        let space = space.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_empty(space) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_alloc`.
    pub fn alloc(set: Set, aff: Aff) -> PwAff {
        let set = set.ptr;
        let aff = aff.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_alloc(set, aff) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_zero_on_domain`.
    pub fn zero_on_domain(ls: LocalSpace) -> PwAff {
        let ls = ls.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_zero_on_domain(ls) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_var_on_domain`.
    pub fn var_on_domain(ls: LocalSpace, type_: DimType, pos: u32) -> PwAff {
        let ls = ls.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_var_on_domain(ls, type_, pos) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_nan_on_domain_space`.
    pub fn nan_on_domain_space(space: Space) -> PwAff {
        let space = space.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_nan_on_domain_space(space) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_nan_on_domain`.
    pub fn nan_on_domain(ls: LocalSpace) -> PwAff {
        let ls = ls.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_nan_on_domain(ls) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_val_on_domain`.
    pub fn val_on_domain(domain: Set, v: Val) -> PwAff {
        let domain = domain.ptr;
        let v = v.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_val_on_domain(domain, v) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_param_on_domain_id`.
    pub fn param_on_domain_id(domain: Set, id: Id) -> PwAff {
        let domain = domain.ptr;
        let id = id.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_param_on_domain_id(domain, id) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_get_dim_name`.
    pub fn get_dim_name(&self, type_: DimType, pos: u32) -> &str {
        let pa = self;
        let pa = pa.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_get_dim_name(pa, type_, pos) };
        let isl_rs_result = unsafe { CStr::from_ptr(isl_rs_result) };
        let isl_rs_result = isl_rs_result.to_str().unwrap();
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_has_dim_id`.
    pub fn has_dim_id(&self, type_: DimType, pos: u32) -> bool {
        let pa = self;
        let pa = pa.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_has_dim_id(pa, type_, pos) };
        let isl_rs_result = match isl_rs_result {
            0 => false,
            1 => true,
            _ => panic!("Got isl_bool = -1"),
        };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_get_dim_id`.
    pub fn get_dim_id(&self, type_: DimType, pos: u32) -> Id {
        let pa = self;
        let pa = pa.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_get_dim_id(pa, type_, pos) };
        let isl_rs_result = Id { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_set_dim_id`.
    pub fn set_dim_id(self, type_: DimType, pos: u32, id: Id) -> PwAff {
        let pma = self;
        let pma = pma.ptr;
        let id = id.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_set_dim_id(pma, type_, pos, id) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_find_dim_by_name`.
    pub fn find_dim_by_name(&self, type_: DimType, name: &str) -> i32 {
        let pa = self;
        let pa = pa.ptr;
        let name = CString::new(name).unwrap();
        let name = name.as_ptr();
        let isl_rs_result = unsafe { isl_pw_aff_find_dim_by_name(pa, type_, name) };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_is_empty`.
    pub fn is_empty(&self) -> bool {
        let pwaff = self;
        let pwaff = pwaff.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_is_empty(pwaff) };
        let isl_rs_result = match isl_rs_result {
            0 => false,
            1 => true,
            _ => panic!("Got isl_bool = -1"),
        };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_involves_nan`.
    pub fn involves_nan(&self) -> bool {
        let pa = self;
        let pa = pa.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_involves_nan(pa) };
        let isl_rs_result = match isl_rs_result {
            0 => false,
            1 => true,
            _ => panic!("Got isl_bool = -1"),
        };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_plain_cmp`.
    pub fn plain_cmp(&self, pa2: &PwAff) -> i32 {
        let pa1 = self;
        let pa1 = pa1.ptr;
        let pa2 = pa2.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_plain_cmp(pa1, pa2) };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_plain_is_equal`.
    pub fn plain_is_equal(&self, pwaff2: &PwAff) -> bool {
        let pwaff1 = self;
        let pwaff1 = pwaff1.ptr;
        let pwaff2 = pwaff2.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_plain_is_equal(pwaff1, pwaff2) };
        let isl_rs_result = match isl_rs_result {
            0 => false,
            1 => true,
            _ => panic!("Got isl_bool = -1"),
        };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_is_equal`.
    pub fn is_equal(&self, pa2: &PwAff) -> bool {
        let pa1 = self;
        let pa1 = pa1.ptr;
        let pa2 = pa2.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_is_equal(pa1, pa2) };
        let isl_rs_result = match isl_rs_result {
            0 => false,
            1 => true,
            _ => panic!("Got isl_bool = -1"),
        };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_union_min`.
    pub fn union_min(self, pwaff2: PwAff) -> PwAff {
        let pwaff1 = self;
        let pwaff1 = pwaff1.ptr;
        let pwaff2 = pwaff2.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_union_min(pwaff1, pwaff2) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_union_max`.
    pub fn union_max(self, pwaff2: PwAff) -> PwAff {
        let pwaff1 = self;
        let pwaff1 = pwaff1.ptr;
        let pwaff2 = pwaff2.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_union_max(pwaff1, pwaff2) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_union_add`.
    pub fn union_add(self, pwaff2: PwAff) -> PwAff {
        let pwaff1 = self;
        let pwaff1 = pwaff1.ptr;
        let pwaff2 = pwaff2.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_union_add(pwaff1, pwaff2) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_copy`.
    pub fn copy(&self) -> PwAff {
        let pwaff = self;
        let pwaff = pwaff.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_copy(pwaff) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_free`.
    pub fn free(self) -> PwAff {
        let pwaff = self;
        let pwaff = pwaff.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_free(pwaff) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_dim`.
    pub fn dim(&self, type_: DimType) -> i32 {
        let pwaff = self;
        let pwaff = pwaff.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_dim(pwaff, type_) };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_involves_param_id`.
    pub fn involves_param_id(&self, id: &Id) -> bool {
        let pa = self;
        let pa = pa.ptr;
        let id = id.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_involves_param_id(pa, id) };
        let isl_rs_result = match isl_rs_result {
            0 => false,
            1 => true,
            _ => panic!("Got isl_bool = -1"),
        };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_involves_dims`.
    pub fn involves_dims(&self, type_: DimType, first: u32, n: u32) -> bool {
        let pwaff = self;
        let pwaff = pwaff.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_involves_dims(pwaff, type_, first, n) };
        let isl_rs_result = match isl_rs_result {
            0 => false,
            1 => true,
            _ => panic!("Got isl_bool = -1"),
        };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_is_cst`.
    pub fn is_cst(&self) -> bool {
        let pwaff = self;
        let pwaff = pwaff.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_is_cst(pwaff) };
        let isl_rs_result = match isl_rs_result {
            0 => false,
            1 => true,
            _ => panic!("Got isl_bool = -1"),
        };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_insert_domain`.
    pub fn insert_domain(self, domain: Space) -> PwAff {
        let pa = self;
        let pa = pa.ptr;
        let domain = domain.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_insert_domain(pa, domain) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_project_domain_on_params`.
    pub fn project_domain_on_params(self) -> PwAff {
        let pa = self;
        let pa = pa.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_project_domain_on_params(pa) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_align_params`.
    pub fn align_params(self, model: Space) -> PwAff {
        let pwaff = self;
        let pwaff = pwaff.ptr;
        let model = model.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_align_params(pwaff, model) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_drop_unused_params`.
    pub fn drop_unused_params(self) -> PwAff {
        let pa = self;
        let pa = pa.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_drop_unused_params(pa) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_has_tuple_id`.
    pub fn has_tuple_id(&self, type_: DimType) -> bool {
        let pa = self;
        let pa = pa.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_has_tuple_id(pa, type_) };
        let isl_rs_result = match isl_rs_result {
            0 => false,
            1 => true,
            _ => panic!("Got isl_bool = -1"),
        };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_get_tuple_id`.
    pub fn get_tuple_id(&self, type_: DimType) -> Id {
        let pa = self;
        let pa = pa.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_get_tuple_id(pa, type_) };
        let isl_rs_result = Id { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_set_tuple_id`.
    pub fn set_tuple_id(self, type_: DimType, id: Id) -> PwAff {
        let pwaff = self;
        let pwaff = pwaff.ptr;
        let id = id.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_set_tuple_id(pwaff, type_, id) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_reset_tuple_id`.
    pub fn reset_tuple_id(self, type_: DimType) -> PwAff {
        let pa = self;
        let pa = pa.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_reset_tuple_id(pa, type_) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_reset_user`.
    pub fn reset_user(self) -> PwAff {
        let pa = self;
        let pa = pa.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_reset_user(pa) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_params`.
    pub fn params(self) -> Set {
        let pwa = self;
        let pwa = pwa.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_params(pwa) };
        let isl_rs_result = Set { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_domain`.
    pub fn domain(self) -> Set {
        let pwaff = self;
        let pwaff = pwaff.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_domain(pwaff) };
        let isl_rs_result = Set { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_from_range`.
    pub fn from_range(self) -> PwAff {
        let pwa = self;
        let pwa = pwa.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_from_range(pwa) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_min`.
    pub fn min(self, pwaff2: PwAff) -> PwAff {
        let pwaff1 = self;
        let pwaff1 = pwaff1.ptr;
        let pwaff2 = pwaff2.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_min(pwaff1, pwaff2) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_max`.
    pub fn max(self, pwaff2: PwAff) -> PwAff {
        let pwaff1 = self;
        let pwaff1 = pwaff1.ptr;
        let pwaff2 = pwaff2.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_max(pwaff1, pwaff2) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_mul`.
    pub fn mul(self, pwaff2: PwAff) -> PwAff {
        let pwaff1 = self;
        let pwaff1 = pwaff1.ptr;
        let pwaff2 = pwaff2.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_mul(pwaff1, pwaff2) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_div`.
    pub fn div(self, pa2: PwAff) -> PwAff {
        let pa1 = self;
        let pa1 = pa1.ptr;
        let pa2 = pa2.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_div(pa1, pa2) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_add`.
    pub fn add(self, pwaff2: PwAff) -> PwAff {
        let pwaff1 = self;
        let pwaff1 = pwaff1.ptr;
        let pwaff2 = pwaff2.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_add(pwaff1, pwaff2) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_sub`.
    pub fn sub(self, pwaff2: PwAff) -> PwAff {
        let pwaff1 = self;
        let pwaff1 = pwaff1.ptr;
        let pwaff2 = pwaff2.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_sub(pwaff1, pwaff2) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_neg`.
    pub fn neg(self) -> PwAff {
        let pwaff = self;
        let pwaff = pwaff.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_neg(pwaff) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_ceil`.
    pub fn ceil(self) -> PwAff {
        let pwaff = self;
        let pwaff = pwaff.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_ceil(pwaff) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_floor`.
    pub fn floor(self) -> PwAff {
        let pwaff = self;
        let pwaff = pwaff.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_floor(pwaff) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_mod_val`.
    pub fn mod_val(self, mod_: Val) -> PwAff {
        let pa = self;
        let pa = pa.ptr;
        let mod_ = mod_.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_mod_val(pa, mod_) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_tdiv_q`.
    pub fn tdiv_q(self, pa2: PwAff) -> PwAff {
        let pa1 = self;
        let pa1 = pa1.ptr;
        let pa2 = pa2.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_tdiv_q(pa1, pa2) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_tdiv_r`.
    pub fn tdiv_r(self, pa2: PwAff) -> PwAff {
        let pa1 = self;
        let pa1 = pa1.ptr;
        let pa2 = pa2.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_tdiv_r(pa1, pa2) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_intersect_params`.
    pub fn intersect_params(self, set: Set) -> PwAff {
        let pa = self;
        let pa = pa.ptr;
        let set = set.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_intersect_params(pa, set) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_intersect_domain`.
    pub fn intersect_domain(self, set: Set) -> PwAff {
        let pa = self;
        let pa = pa.ptr;
        let set = set.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_intersect_domain(pa, set) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_intersect_domain_wrapped_domain`.
    pub fn intersect_domain_wrapped_domain(self, set: Set) -> PwAff {
        let pa = self;
        let pa = pa.ptr;
        let set = set.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_intersect_domain_wrapped_domain(pa, set) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_intersect_domain_wrapped_range`.
    pub fn intersect_domain_wrapped_range(self, set: Set) -> PwAff {
        let pa = self;
        let pa = pa.ptr;
        let set = set.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_intersect_domain_wrapped_range(pa, set) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_subtract_domain`.
    pub fn subtract_domain(self, set: Set) -> PwAff {
        let pa = self;
        let pa = pa.ptr;
        let set = set.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_subtract_domain(pa, set) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_cond`.
    pub fn cond(self, pwaff_true: PwAff, pwaff_false: PwAff) -> PwAff {
        let cond = self;
        let cond = cond.ptr;
        let pwaff_true = pwaff_true.ptr;
        let pwaff_false = pwaff_false.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_cond(cond, pwaff_true, pwaff_false) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_add_constant_val`.
    pub fn add_constant_val(self, v: Val) -> PwAff {
        let pa = self;
        let pa = pa.ptr;
        let v = v.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_add_constant_val(pa, v) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_scale_val`.
    pub fn scale_val(self, v: Val) -> PwAff {
        let pa = self;
        let pa = pa.ptr;
        let v = v.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_scale_val(pa, v) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_scale_down_val`.
    pub fn scale_down_val(self, f: Val) -> PwAff {
        let pa = self;
        let pa = pa.ptr;
        let f = f.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_scale_down_val(pa, f) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_insert_dims`.
    pub fn insert_dims(self, type_: DimType, first: u32, n: u32) -> PwAff {
        let pwaff = self;
        let pwaff = pwaff.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_insert_dims(pwaff, type_, first, n) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_add_dims`.
    pub fn add_dims(self, type_: DimType, n: u32) -> PwAff {
        let pwaff = self;
        let pwaff = pwaff.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_add_dims(pwaff, type_, n) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_move_dims`.
    pub fn move_dims(self, dst_type: DimType, dst_pos: u32, src_type: DimType, src_pos: u32,
                     n: u32)
                     -> PwAff {
        let pa = self;
        let pa = pa.ptr;
        let isl_rs_result =
            unsafe { isl_pw_aff_move_dims(pa, dst_type, dst_pos, src_type, src_pos, n) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_drop_dims`.
    pub fn drop_dims(self, type_: DimType, first: u32, n: u32) -> PwAff {
        let pwaff = self;
        let pwaff = pwaff.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_drop_dims(pwaff, type_, first, n) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_coalesce`.
    pub fn coalesce(self) -> PwAff {
        let pa = self;
        let pa = pa.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_coalesce(pa) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_gist`.
    pub fn gist(self, context: Set) -> PwAff {
        let pwaff = self;
        let pwaff = pwaff.ptr;
        let context = context.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_gist(pwaff, context) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_gist_params`.
    pub fn gist_params(self, context: Set) -> PwAff {
        let pwaff = self;
        let pwaff = pwaff.ptr;
        let context = context.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_gist_params(pwaff, context) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_eval`.
    pub fn eval(self, pnt: Point) -> Val {
        let pa = self;
        let pa = pa.ptr;
        let pnt = pnt.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_eval(pa, pnt) };
        let isl_rs_result = Val { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_n_piece`.
    pub fn n_piece(&self) -> i32 {
        let pwaff = self;
        let pwaff = pwaff.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_n_piece(pwaff) };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_isa_aff`.
    pub fn isa_aff(&self) -> bool {
        let pa = self;
        let pa = pa.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_isa_aff(pa) };
        let isl_rs_result = match isl_rs_result {
            0 => false,
            1 => true,
            _ => panic!("Got isl_bool = -1"),
        };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_as_aff`.
    pub fn as_aff(self) -> Aff {
        let pa = self;
        let pa = pa.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_as_aff(pa) };
        let isl_rs_result = Aff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_as_map`.
    pub fn as_map(self) -> Map {
        let pa = self;
        let pa = pa.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_as_map(pa) };
        let isl_rs_result = Map { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_pos_set`.
    pub fn pos_set(self) -> Set {
        let pa = self;
        let pa = pa.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_pos_set(pa) };
        let isl_rs_result = Set { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_nonneg_set`.
    pub fn nonneg_set(self) -> Set {
        let pwaff = self;
        let pwaff = pwaff.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_nonneg_set(pwaff) };
        let isl_rs_result = Set { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_zero_set`.
    pub fn zero_set(self) -> Set {
        let pwaff = self;
        let pwaff = pwaff.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_zero_set(pwaff) };
        let isl_rs_result = Set { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_non_zero_set`.
    pub fn non_zero_set(self) -> Set {
        let pwaff = self;
        let pwaff = pwaff.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_non_zero_set(pwaff) };
        let isl_rs_result = Set { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_eq_set`.
    pub fn eq_set(self, pwaff2: PwAff) -> Set {
        let pwaff1 = self;
        let pwaff1 = pwaff1.ptr;
        let pwaff2 = pwaff2.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_eq_set(pwaff1, pwaff2) };
        let isl_rs_result = Set { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_ne_set`.
    pub fn ne_set(self, pwaff2: PwAff) -> Set {
        let pwaff1 = self;
        let pwaff1 = pwaff1.ptr;
        let pwaff2 = pwaff2.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_ne_set(pwaff1, pwaff2) };
        let isl_rs_result = Set { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_le_set`.
    pub fn le_set(self, pwaff2: PwAff) -> Set {
        let pwaff1 = self;
        let pwaff1 = pwaff1.ptr;
        let pwaff2 = pwaff2.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_le_set(pwaff1, pwaff2) };
        let isl_rs_result = Set { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_lt_set`.
    pub fn lt_set(self, pwaff2: PwAff) -> Set {
        let pwaff1 = self;
        let pwaff1 = pwaff1.ptr;
        let pwaff2 = pwaff2.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_lt_set(pwaff1, pwaff2) };
        let isl_rs_result = Set { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_ge_set`.
    pub fn ge_set(self, pwaff2: PwAff) -> Set {
        let pwaff1 = self;
        let pwaff1 = pwaff1.ptr;
        let pwaff2 = pwaff2.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_ge_set(pwaff1, pwaff2) };
        let isl_rs_result = Set { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_gt_set`.
    pub fn gt_set(self, pwaff2: PwAff) -> Set {
        let pwaff1 = self;
        let pwaff1 = pwaff1.ptr;
        let pwaff2 = pwaff2.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_gt_set(pwaff1, pwaff2) };
        let isl_rs_result = Set { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_eq_map`.
    pub fn eq_map(self, pa2: PwAff) -> Map {
        let pa1 = self;
        let pa1 = pa1.ptr;
        let pa2 = pa2.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_eq_map(pa1, pa2) };
        let isl_rs_result = Map { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_le_map`.
    pub fn le_map(self, pa2: PwAff) -> Map {
        let pa1 = self;
        let pa1 = pa1.ptr;
        let pa2 = pa2.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_le_map(pa1, pa2) };
        let isl_rs_result = Map { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_lt_map`.
    pub fn lt_map(self, pa2: PwAff) -> Map {
        let pa1 = self;
        let pa1 = pa1.ptr;
        let pa2 = pa2.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_lt_map(pa1, pa2) };
        let isl_rs_result = Map { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_ge_map`.
    pub fn ge_map(self, pa2: PwAff) -> Map {
        let pa1 = self;
        let pa1 = pa1.ptr;
        let pa2 = pa2.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_ge_map(pa1, pa2) };
        let isl_rs_result = Map { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_gt_map`.
    pub fn gt_map(self, pa2: PwAff) -> Map {
        let pa1 = self;
        let pa1 = pa1.ptr;
        let pa2 = pa2.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_gt_map(pa1, pa2) };
        let isl_rs_result = Map { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_bind_id`.
    pub fn bind_id(self, id: Id) -> Set {
        let pa = self;
        let pa = pa.ptr;
        let id = id.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_bind_id(pa, id) };
        let isl_rs_result = Set { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_read_from_str`.
    pub fn read_from_str(ctx: &Context, str_: &str) -> PwAff {
        let ctx = ctx.ptr;
        let str_ = CString::new(str_).unwrap();
        let str_ = str_.as_ptr();
        let isl_rs_result = unsafe { isl_pw_aff_read_from_str(ctx, str_) };
        let isl_rs_result = PwAff { ptr: isl_rs_result };
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_to_str`.
    pub fn to_str(&self) -> &str {
        let pa = self;
        let pa = pa.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_to_str(pa) };
        let isl_rs_result = unsafe { CStr::from_ptr(isl_rs_result) };
        let isl_rs_result = isl_rs_result.to_str().unwrap();
        isl_rs_result
    }

    /// Wraps `isl_pw_aff_dump`.
    pub fn dump(&self) {
        let pwaff = self;
        let pwaff = pwaff.ptr;
        let isl_rs_result = unsafe { isl_pw_aff_dump(pwaff) };
        isl_rs_result
    }
}

impl Drop for PwAff {
    fn drop(&mut self) {
        unsafe {
            isl_pw_aff_free(self.ptr);
        }
    }
}
