// Automatically generated by isl_bindings_generator.
// LICENSE: MIT

use super::{Context, PwMultiAff};
use libc::uintptr_t;
use std::ffi::{CStr, CString};
use std::os::raw::c_char;

/// Wraps `isl_pw_multi_aff_list`.
pub struct PwMultiAffList {
    pub ptr: uintptr_t,
    pub should_free_on_drop: bool,
}

extern "C" {

    fn isl_pw_multi_aff_list_add(list: uintptr_t, el: uintptr_t) -> uintptr_t;

    fn isl_pw_multi_aff_list_alloc(ctx: uintptr_t, n: i32) -> uintptr_t;

    fn isl_pw_multi_aff_list_clear(list: uintptr_t) -> uintptr_t;

    fn isl_pw_multi_aff_list_concat(list1: uintptr_t, list2: uintptr_t) -> uintptr_t;

    fn isl_pw_multi_aff_list_copy(list: uintptr_t) -> uintptr_t;

    fn isl_pw_multi_aff_list_drop(list: uintptr_t, first: u32, n: u32) -> uintptr_t;

    fn isl_pw_multi_aff_list_dump(list: uintptr_t) -> ();

    fn isl_pw_multi_aff_list_free(list: uintptr_t) -> uintptr_t;

    fn isl_pw_multi_aff_list_from_pw_multi_aff(el: uintptr_t) -> uintptr_t;

    fn isl_pw_multi_aff_list_get_at(list: uintptr_t, index: i32) -> uintptr_t;

    fn isl_pw_multi_aff_list_get_ctx(list: uintptr_t) -> uintptr_t;

    fn isl_pw_multi_aff_list_get_pw_multi_aff(list: uintptr_t, index: i32) -> uintptr_t;

    fn isl_pw_multi_aff_list_insert(list: uintptr_t, pos: u32, el: uintptr_t) -> uintptr_t;

    fn isl_pw_multi_aff_list_n_pw_multi_aff(list: uintptr_t) -> i32;

    fn isl_pw_multi_aff_list_read_from_str(ctx: uintptr_t, str_: *const c_char) -> uintptr_t;

    fn isl_pw_multi_aff_list_reverse(list: uintptr_t) -> uintptr_t;

    fn isl_pw_multi_aff_list_set_at(list: uintptr_t, index: i32, el: uintptr_t) -> uintptr_t;

    fn isl_pw_multi_aff_list_set_pw_multi_aff(list: uintptr_t, index: i32, el: uintptr_t)
                                              -> uintptr_t;

    fn isl_pw_multi_aff_list_size(list: uintptr_t) -> i32;

    fn isl_pw_multi_aff_list_swap(list: uintptr_t, pos1: u32, pos2: u32) -> uintptr_t;

    fn isl_pw_multi_aff_list_to_str(list: uintptr_t) -> *const c_char;

}

impl PwMultiAffList {
    /// Wraps `isl_pw_multi_aff_list_add`.
    pub fn add(self, el: PwMultiAff) -> PwMultiAffList {
        let list = self;
        let mut list = list;
        list.do_not_free_on_drop();
        let list = list.ptr;
        let mut el = el;
        el.do_not_free_on_drop();
        let el = el.ptr;
        let isl_rs_result = unsafe { isl_pw_multi_aff_list_add(list, el) };
        let isl_rs_result = PwMultiAffList { ptr: isl_rs_result,
                                             should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_pw_multi_aff_list_alloc`.
    pub fn alloc(ctx: &Context, n: i32) -> PwMultiAffList {
        let ctx = ctx.ptr;
        let isl_rs_result = unsafe { isl_pw_multi_aff_list_alloc(ctx, n) };
        let isl_rs_result = PwMultiAffList { ptr: isl_rs_result,
                                             should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_pw_multi_aff_list_clear`.
    pub fn clear(self) -> PwMultiAffList {
        let list = self;
        let mut list = list;
        list.do_not_free_on_drop();
        let list = list.ptr;
        let isl_rs_result = unsafe { isl_pw_multi_aff_list_clear(list) };
        let isl_rs_result = PwMultiAffList { ptr: isl_rs_result,
                                             should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_pw_multi_aff_list_concat`.
    pub fn concat(self, list2: PwMultiAffList) -> PwMultiAffList {
        let list1 = self;
        let mut list1 = list1;
        list1.do_not_free_on_drop();
        let list1 = list1.ptr;
        let mut list2 = list2;
        list2.do_not_free_on_drop();
        let list2 = list2.ptr;
        let isl_rs_result = unsafe { isl_pw_multi_aff_list_concat(list1, list2) };
        let isl_rs_result = PwMultiAffList { ptr: isl_rs_result,
                                             should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_pw_multi_aff_list_copy`.
    pub fn copy(&self) -> PwMultiAffList {
        let list = self;
        let list = list.ptr;
        let isl_rs_result = unsafe { isl_pw_multi_aff_list_copy(list) };
        let isl_rs_result = PwMultiAffList { ptr: isl_rs_result,
                                             should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_pw_multi_aff_list_drop`.
    pub fn drop(self, first: u32, n: u32) -> PwMultiAffList {
        let list = self;
        let mut list = list;
        list.do_not_free_on_drop();
        let list = list.ptr;
        let isl_rs_result = unsafe { isl_pw_multi_aff_list_drop(list, first, n) };
        let isl_rs_result = PwMultiAffList { ptr: isl_rs_result,
                                             should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_pw_multi_aff_list_dump`.
    pub fn dump(&self) -> () {
        let list = self;
        let list = list.ptr;
        let isl_rs_result = unsafe { isl_pw_multi_aff_list_dump(list) };
        isl_rs_result
    }

    /// Wraps `isl_pw_multi_aff_list_free`.
    pub fn free(self) -> PwMultiAffList {
        let list = self;
        let mut list = list;
        list.do_not_free_on_drop();
        let list = list.ptr;
        let isl_rs_result = unsafe { isl_pw_multi_aff_list_free(list) };
        let isl_rs_result = PwMultiAffList { ptr: isl_rs_result,
                                             should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_pw_multi_aff_list_from_pw_multi_aff`.
    pub fn from_pw_multi_aff(el: PwMultiAff) -> PwMultiAffList {
        let mut el = el;
        el.do_not_free_on_drop();
        let el = el.ptr;
        let isl_rs_result = unsafe { isl_pw_multi_aff_list_from_pw_multi_aff(el) };
        let isl_rs_result = PwMultiAffList { ptr: isl_rs_result,
                                             should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_pw_multi_aff_list_get_at`.
    pub fn get_at(&self, index: i32) -> PwMultiAff {
        let list = self;
        let list = list.ptr;
        let isl_rs_result = unsafe { isl_pw_multi_aff_list_get_at(list, index) };
        let isl_rs_result = PwMultiAff { ptr: isl_rs_result,
                                         should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_pw_multi_aff_list_get_ctx`.
    pub fn get_ctx(&self) -> Context {
        let list = self;
        let list = list.ptr;
        let isl_rs_result = unsafe { isl_pw_multi_aff_list_get_ctx(list) };
        let isl_rs_result = Context { ptr: isl_rs_result,
                                      should_free_on_drop: false };
        isl_rs_result
    }

    /// Wraps `isl_pw_multi_aff_list_get_pw_multi_aff`.
    pub fn get_pw_multi_aff(&self, index: i32) -> PwMultiAff {
        let list = self;
        let list = list.ptr;
        let isl_rs_result = unsafe { isl_pw_multi_aff_list_get_pw_multi_aff(list, index) };
        let isl_rs_result = PwMultiAff { ptr: isl_rs_result,
                                         should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_pw_multi_aff_list_insert`.
    pub fn insert(self, pos: u32, el: PwMultiAff) -> PwMultiAffList {
        let list = self;
        let mut list = list;
        list.do_not_free_on_drop();
        let list = list.ptr;
        let mut el = el;
        el.do_not_free_on_drop();
        let el = el.ptr;
        let isl_rs_result = unsafe { isl_pw_multi_aff_list_insert(list, pos, el) };
        let isl_rs_result = PwMultiAffList { ptr: isl_rs_result,
                                             should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_pw_multi_aff_list_n_pw_multi_aff`.
    pub fn n_pw_multi_aff(&self) -> i32 {
        let list = self;
        let list = list.ptr;
        let isl_rs_result = unsafe { isl_pw_multi_aff_list_n_pw_multi_aff(list) };
        isl_rs_result
    }

    /// Wraps `isl_pw_multi_aff_list_read_from_str`.
    pub fn read_from_str(ctx: &Context, str_: &str) -> PwMultiAffList {
        let ctx = ctx.ptr;
        let str_ = CString::new(str_).unwrap();
        let str_ = str_.as_ptr();
        let isl_rs_result = unsafe { isl_pw_multi_aff_list_read_from_str(ctx, str_) };
        let isl_rs_result = PwMultiAffList { ptr: isl_rs_result,
                                             should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_pw_multi_aff_list_reverse`.
    pub fn reverse(self) -> PwMultiAffList {
        let list = self;
        let mut list = list;
        list.do_not_free_on_drop();
        let list = list.ptr;
        let isl_rs_result = unsafe { isl_pw_multi_aff_list_reverse(list) };
        let isl_rs_result = PwMultiAffList { ptr: isl_rs_result,
                                             should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_pw_multi_aff_list_set_at`.
    pub fn set_at(self, index: i32, el: PwMultiAff) -> PwMultiAffList {
        let list = self;
        let mut list = list;
        list.do_not_free_on_drop();
        let list = list.ptr;
        let mut el = el;
        el.do_not_free_on_drop();
        let el = el.ptr;
        let isl_rs_result = unsafe { isl_pw_multi_aff_list_set_at(list, index, el) };
        let isl_rs_result = PwMultiAffList { ptr: isl_rs_result,
                                             should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_pw_multi_aff_list_set_pw_multi_aff`.
    pub fn set_pw_multi_aff(self, index: i32, el: PwMultiAff) -> PwMultiAffList {
        let list = self;
        let mut list = list;
        list.do_not_free_on_drop();
        let list = list.ptr;
        let mut el = el;
        el.do_not_free_on_drop();
        let el = el.ptr;
        let isl_rs_result = unsafe { isl_pw_multi_aff_list_set_pw_multi_aff(list, index, el) };
        let isl_rs_result = PwMultiAffList { ptr: isl_rs_result,
                                             should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_pw_multi_aff_list_size`.
    pub fn size(&self) -> i32 {
        let list = self;
        let list = list.ptr;
        let isl_rs_result = unsafe { isl_pw_multi_aff_list_size(list) };
        isl_rs_result
    }

    /// Wraps `isl_pw_multi_aff_list_swap`.
    pub fn swap(self, pos1: u32, pos2: u32) -> PwMultiAffList {
        let list = self;
        let mut list = list;
        list.do_not_free_on_drop();
        let list = list.ptr;
        let isl_rs_result = unsafe { isl_pw_multi_aff_list_swap(list, pos1, pos2) };
        let isl_rs_result = PwMultiAffList { ptr: isl_rs_result,
                                             should_free_on_drop: true };
        isl_rs_result
    }

    /// Wraps `isl_pw_multi_aff_list_to_str`.
    pub fn to_str(&self) -> &str {
        let list = self;
        let list = list.ptr;
        let isl_rs_result = unsafe { isl_pw_multi_aff_list_to_str(list) };
        let isl_rs_result = unsafe { CStr::from_ptr(isl_rs_result) };
        let isl_rs_result = isl_rs_result.to_str().unwrap();
        isl_rs_result
    }

    /// Does not call isl_pw_multi_aff_list_free() on being dropped. (For
    /// internal use only.)
    pub fn do_not_free_on_drop(&mut self) {
        self.should_free_on_drop = false;
    }
}

impl Drop for PwMultiAffList {
    fn drop(&mut self) {
        if self.should_free_on_drop {
            unsafe {
                isl_pw_multi_aff_list_free(self.ptr);
            }
        }
    }
}
