// Automatically generated by isl_bindings_generator.
// LICENSE: MIT

use super::{
    Context, DimType, Error, LibISLError, Point, PwQPolynomial, PwQPolynomialList, Set, Space,
    UnionSet, Val,
};
use libc::uintptr_t;
use std::ffi::{CStr, CString};
use std::os::raw::c_char;

/// Wraps `isl_union_pw_qpolynomial`.
pub struct UnionPwQPolynomial {
    pub ptr: uintptr_t,
    pub should_free_on_drop: bool,
}

extern "C" {

    fn isl_union_pw_qpolynomial_add(upwqp1: uintptr_t, upwqp2: uintptr_t) -> uintptr_t;

    fn isl_union_pw_qpolynomial_add_pw_qpolynomial(upwqp: uintptr_t, pwqp: uintptr_t) -> uintptr_t;

    fn isl_union_pw_qpolynomial_align_params(upwqp: uintptr_t, model: uintptr_t) -> uintptr_t;

    fn isl_union_pw_qpolynomial_coalesce(upwqp: uintptr_t) -> uintptr_t;

    fn isl_union_pw_qpolynomial_copy(upwqp: uintptr_t) -> uintptr_t;

    fn isl_union_pw_qpolynomial_dim(upwqp: uintptr_t, type_: i32) -> i32;

    fn isl_union_pw_qpolynomial_domain(upwqp: uintptr_t) -> uintptr_t;

    fn isl_union_pw_qpolynomial_domain_reverse(upwqp: uintptr_t) -> uintptr_t;

    fn isl_union_pw_qpolynomial_drop_dims(upwqp: uintptr_t, type_: i32, first: u32, n: u32)
                                          -> uintptr_t;

    fn isl_union_pw_qpolynomial_drop_unused_params(upwqp: uintptr_t) -> uintptr_t;

    fn isl_union_pw_qpolynomial_eval(upwqp: uintptr_t, pnt: uintptr_t) -> uintptr_t;

    fn isl_union_pw_qpolynomial_extract_pw_qpolynomial(upwqp: uintptr_t, space: uintptr_t)
                                                       -> uintptr_t;

    fn isl_union_pw_qpolynomial_find_dim_by_name(upwqp: uintptr_t, type_: i32, name: *const c_char)
                                                 -> i32;

    fn isl_union_pw_qpolynomial_free(upwqp: uintptr_t) -> uintptr_t;

    fn isl_union_pw_qpolynomial_from_pw_qpolynomial(pwqp: uintptr_t) -> uintptr_t;

    fn isl_union_pw_qpolynomial_get_ctx(upwqp: uintptr_t) -> uintptr_t;

    fn isl_union_pw_qpolynomial_get_pw_qpolynomial_list(upwqp: uintptr_t) -> uintptr_t;

    fn isl_union_pw_qpolynomial_get_space(upwqp: uintptr_t) -> uintptr_t;

    fn isl_union_pw_qpolynomial_gist(upwqp: uintptr_t, context: uintptr_t) -> uintptr_t;

    fn isl_union_pw_qpolynomial_gist_params(upwqp: uintptr_t, context: uintptr_t) -> uintptr_t;

    fn isl_union_pw_qpolynomial_intersect_domain(upwpq: uintptr_t, uset: uintptr_t) -> uintptr_t;

    fn isl_union_pw_qpolynomial_intersect_domain_space(upwpq: uintptr_t, space: uintptr_t)
                                                       -> uintptr_t;

    fn isl_union_pw_qpolynomial_intersect_domain_union_set(upwpq: uintptr_t, uset: uintptr_t)
                                                           -> uintptr_t;

    fn isl_union_pw_qpolynomial_intersect_domain_wrapped_domain(upwpq: uintptr_t, uset: uintptr_t)
                                                                -> uintptr_t;

    fn isl_union_pw_qpolynomial_intersect_domain_wrapped_range(upwpq: uintptr_t, uset: uintptr_t)
                                                               -> uintptr_t;

    fn isl_union_pw_qpolynomial_intersect_params(upwpq: uintptr_t, set: uintptr_t) -> uintptr_t;

    fn isl_union_pw_qpolynomial_involves_nan(upwqp: uintptr_t) -> i32;

    fn isl_union_pw_qpolynomial_mul(upwqp1: uintptr_t, upwqp2: uintptr_t) -> uintptr_t;

    fn isl_union_pw_qpolynomial_n_pw_qpolynomial(upwqp: uintptr_t) -> i32;

    fn isl_union_pw_qpolynomial_neg(upwqp: uintptr_t) -> uintptr_t;

    fn isl_union_pw_qpolynomial_plain_is_equal(upwqp1: uintptr_t, upwqp2: uintptr_t) -> i32;

    fn isl_union_pw_qpolynomial_read_from_str(ctx: uintptr_t, str_: *const c_char) -> uintptr_t;

    fn isl_union_pw_qpolynomial_reset_user(upwqp: uintptr_t) -> uintptr_t;

    fn isl_union_pw_qpolynomial_scale_down_val(upwqp: uintptr_t, v: uintptr_t) -> uintptr_t;

    fn isl_union_pw_qpolynomial_scale_val(upwqp: uintptr_t, v: uintptr_t) -> uintptr_t;

    fn isl_union_pw_qpolynomial_set_dim_name(upwqp: uintptr_t, type_: i32, pos: u32,
                                             s: *const c_char)
                                             -> uintptr_t;

    fn isl_union_pw_qpolynomial_sub(upwqp1: uintptr_t, upwqp2: uintptr_t) -> uintptr_t;

    fn isl_union_pw_qpolynomial_subtract_domain(upwpq: uintptr_t, uset: uintptr_t) -> uintptr_t;

    fn isl_union_pw_qpolynomial_subtract_domain_space(upwpq: uintptr_t, space: uintptr_t)
                                                      -> uintptr_t;

    fn isl_union_pw_qpolynomial_subtract_domain_union_set(upwpq: uintptr_t, uset: uintptr_t)
                                                          -> uintptr_t;

    fn isl_union_pw_qpolynomial_to_polynomial(upwqp: uintptr_t, sign: i32) -> uintptr_t;

    fn isl_union_pw_qpolynomial_to_str(upwqp: uintptr_t) -> *const c_char;

    fn isl_union_pw_qpolynomial_zero(space: uintptr_t) -> uintptr_t;

    fn isl_union_pw_qpolynomial_zero_ctx(ctx: uintptr_t) -> uintptr_t;

    fn isl_union_pw_qpolynomial_zero_space(space: uintptr_t) -> uintptr_t;

}

impl UnionPwQPolynomial {
    /// Wraps `isl_union_pw_qpolynomial_add`.
    pub fn add(self, upwqp2: UnionPwQPolynomial) -> Result<UnionPwQPolynomial, LibISLError> {
        let upwqp1 = self;
        let isl_rs_ctx = upwqp1.get_ctx();
        let mut upwqp1 = upwqp1;
        upwqp1.do_not_free_on_drop();
        let upwqp1 = upwqp1.ptr;
        let mut upwqp2 = upwqp2;
        upwqp2.do_not_free_on_drop();
        let upwqp2 = upwqp2.ptr;
        let isl_rs_result = unsafe { isl_union_pw_qpolynomial_add(upwqp1, upwqp2) };
        let isl_rs_result = UnionPwQPolynomial { ptr: isl_rs_result,
                                                 should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_add_pw_qpolynomial`.
    pub fn add_pw_qpolynomial(self, pwqp: PwQPolynomial)
                              -> Result<UnionPwQPolynomial, LibISLError> {
        let upwqp = self;
        let isl_rs_ctx = upwqp.get_ctx();
        let mut upwqp = upwqp;
        upwqp.do_not_free_on_drop();
        let upwqp = upwqp.ptr;
        let mut pwqp = pwqp;
        pwqp.do_not_free_on_drop();
        let pwqp = pwqp.ptr;
        let isl_rs_result = unsafe { isl_union_pw_qpolynomial_add_pw_qpolynomial(upwqp, pwqp) };
        let isl_rs_result = UnionPwQPolynomial { ptr: isl_rs_result,
                                                 should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_align_params`.
    pub fn align_params(self, model: Space) -> Result<UnionPwQPolynomial, LibISLError> {
        let upwqp = self;
        let isl_rs_ctx = upwqp.get_ctx();
        let mut upwqp = upwqp;
        upwqp.do_not_free_on_drop();
        let upwqp = upwqp.ptr;
        let mut model = model;
        model.do_not_free_on_drop();
        let model = model.ptr;
        let isl_rs_result = unsafe { isl_union_pw_qpolynomial_align_params(upwqp, model) };
        let isl_rs_result = UnionPwQPolynomial { ptr: isl_rs_result,
                                                 should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_coalesce`.
    pub fn coalesce(self) -> Result<UnionPwQPolynomial, LibISLError> {
        let upwqp = self;
        let isl_rs_ctx = upwqp.get_ctx();
        let mut upwqp = upwqp;
        upwqp.do_not_free_on_drop();
        let upwqp = upwqp.ptr;
        let isl_rs_result = unsafe { isl_union_pw_qpolynomial_coalesce(upwqp) };
        let isl_rs_result = UnionPwQPolynomial { ptr: isl_rs_result,
                                                 should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_copy`.
    pub fn copy(&self) -> Result<UnionPwQPolynomial, LibISLError> {
        let upwqp = self;
        let isl_rs_ctx = upwqp.get_ctx();
        let upwqp = upwqp.ptr;
        let isl_rs_result = unsafe { isl_union_pw_qpolynomial_copy(upwqp) };
        let isl_rs_result = UnionPwQPolynomial { ptr: isl_rs_result,
                                                 should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_dim`.
    pub fn dim(&self, type_: DimType) -> Result<i32, LibISLError> {
        let upwqp = self;
        let isl_rs_ctx = upwqp.get_ctx();
        let upwqp = upwqp.ptr;
        let type_ = type_.to_i32();
        let isl_rs_result = unsafe { isl_union_pw_qpolynomial_dim(upwqp, type_) };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_domain`.
    pub fn domain(self) -> Result<UnionSet, LibISLError> {
        let upwqp = self;
        let isl_rs_ctx = upwqp.get_ctx();
        let mut upwqp = upwqp;
        upwqp.do_not_free_on_drop();
        let upwqp = upwqp.ptr;
        let isl_rs_result = unsafe { isl_union_pw_qpolynomial_domain(upwqp) };
        let isl_rs_result = UnionSet { ptr: isl_rs_result,
                                       should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_domain_reverse`.
    pub fn domain_reverse(self) -> Result<UnionPwQPolynomial, LibISLError> {
        let upwqp = self;
        let isl_rs_ctx = upwqp.get_ctx();
        let mut upwqp = upwqp;
        upwqp.do_not_free_on_drop();
        let upwqp = upwqp.ptr;
        let isl_rs_result = unsafe { isl_union_pw_qpolynomial_domain_reverse(upwqp) };
        let isl_rs_result = UnionPwQPolynomial { ptr: isl_rs_result,
                                                 should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_drop_dims`.
    pub fn drop_dims(self, type_: DimType, first: u32, n: u32)
                     -> Result<UnionPwQPolynomial, LibISLError> {
        let upwqp = self;
        let isl_rs_ctx = upwqp.get_ctx();
        let mut upwqp = upwqp;
        upwqp.do_not_free_on_drop();
        let upwqp = upwqp.ptr;
        let type_ = type_.to_i32();
        let isl_rs_result = unsafe { isl_union_pw_qpolynomial_drop_dims(upwqp, type_, first, n) };
        let isl_rs_result = UnionPwQPolynomial { ptr: isl_rs_result,
                                                 should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_drop_unused_params`.
    pub fn drop_unused_params(self) -> Result<UnionPwQPolynomial, LibISLError> {
        let upwqp = self;
        let isl_rs_ctx = upwqp.get_ctx();
        let mut upwqp = upwqp;
        upwqp.do_not_free_on_drop();
        let upwqp = upwqp.ptr;
        let isl_rs_result = unsafe { isl_union_pw_qpolynomial_drop_unused_params(upwqp) };
        let isl_rs_result = UnionPwQPolynomial { ptr: isl_rs_result,
                                                 should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_eval`.
    pub fn eval(self, pnt: Point) -> Result<Val, LibISLError> {
        let upwqp = self;
        let isl_rs_ctx = upwqp.get_ctx();
        let mut upwqp = upwqp;
        upwqp.do_not_free_on_drop();
        let upwqp = upwqp.ptr;
        let mut pnt = pnt;
        pnt.do_not_free_on_drop();
        let pnt = pnt.ptr;
        let isl_rs_result = unsafe { isl_union_pw_qpolynomial_eval(upwqp, pnt) };
        let isl_rs_result = Val { ptr: isl_rs_result,
                                  should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_extract_pw_qpolynomial`.
    pub fn extract_pw_qpolynomial(&self, space: Space) -> Result<PwQPolynomial, LibISLError> {
        let upwqp = self;
        let isl_rs_ctx = upwqp.get_ctx();
        let upwqp = upwqp.ptr;
        let mut space = space;
        space.do_not_free_on_drop();
        let space = space.ptr;
        let isl_rs_result =
            unsafe { isl_union_pw_qpolynomial_extract_pw_qpolynomial(upwqp, space) };
        let isl_rs_result = PwQPolynomial { ptr: isl_rs_result,
                                            should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_find_dim_by_name`.
    pub fn find_dim_by_name(&self, type_: DimType, name: &str) -> Result<i32, LibISLError> {
        let upwqp = self;
        let isl_rs_ctx = upwqp.get_ctx();
        let upwqp = upwqp.ptr;
        let type_ = type_.to_i32();
        let name = CString::new(name).unwrap();
        let name = name.as_ptr();
        let isl_rs_result =
            unsafe { isl_union_pw_qpolynomial_find_dim_by_name(upwqp, type_, name) };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_free`.
    pub fn free(self) -> Result<UnionPwQPolynomial, LibISLError> {
        let upwqp = self;
        let isl_rs_ctx = upwqp.get_ctx();
        let mut upwqp = upwqp;
        upwqp.do_not_free_on_drop();
        let upwqp = upwqp.ptr;
        let isl_rs_result = unsafe { isl_union_pw_qpolynomial_free(upwqp) };
        let isl_rs_result = UnionPwQPolynomial { ptr: isl_rs_result,
                                                 should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_from_pw_qpolynomial`.
    pub fn from_pw_qpolynomial(pwqp: PwQPolynomial) -> Result<UnionPwQPolynomial, LibISLError> {
        let isl_rs_ctx = pwqp.get_ctx();
        let mut pwqp = pwqp;
        pwqp.do_not_free_on_drop();
        let pwqp = pwqp.ptr;
        let isl_rs_result = unsafe { isl_union_pw_qpolynomial_from_pw_qpolynomial(pwqp) };
        let isl_rs_result = UnionPwQPolynomial { ptr: isl_rs_result,
                                                 should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_get_ctx`.
    pub fn get_ctx(&self) -> Context {
        let upwqp = self;
        let upwqp = upwqp.ptr;
        let isl_rs_result = unsafe { isl_union_pw_qpolynomial_get_ctx(upwqp) };
        let isl_rs_result = Context { ptr: isl_rs_result,
                                      should_free_on_drop: false };
        isl_rs_result
    }

    /// Wraps `isl_union_pw_qpolynomial_get_pw_qpolynomial_list`.
    pub fn get_pw_qpolynomial_list(&self) -> Result<PwQPolynomialList, LibISLError> {
        let upwqp = self;
        let isl_rs_ctx = upwqp.get_ctx();
        let upwqp = upwqp.ptr;
        let isl_rs_result = unsafe { isl_union_pw_qpolynomial_get_pw_qpolynomial_list(upwqp) };
        let isl_rs_result = PwQPolynomialList { ptr: isl_rs_result,
                                                should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_get_space`.
    pub fn get_space(&self) -> Result<Space, LibISLError> {
        let upwqp = self;
        let isl_rs_ctx = upwqp.get_ctx();
        let upwqp = upwqp.ptr;
        let isl_rs_result = unsafe { isl_union_pw_qpolynomial_get_space(upwqp) };
        let isl_rs_result = Space { ptr: isl_rs_result,
                                    should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_gist`.
    pub fn gist(self, context: UnionSet) -> Result<UnionPwQPolynomial, LibISLError> {
        let upwqp = self;
        let isl_rs_ctx = upwqp.get_ctx();
        let mut upwqp = upwqp;
        upwqp.do_not_free_on_drop();
        let upwqp = upwqp.ptr;
        let mut context = context;
        context.do_not_free_on_drop();
        let context = context.ptr;
        let isl_rs_result = unsafe { isl_union_pw_qpolynomial_gist(upwqp, context) };
        let isl_rs_result = UnionPwQPolynomial { ptr: isl_rs_result,
                                                 should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_gist_params`.
    pub fn gist_params(self, context: Set) -> Result<UnionPwQPolynomial, LibISLError> {
        let upwqp = self;
        let isl_rs_ctx = upwqp.get_ctx();
        let mut upwqp = upwqp;
        upwqp.do_not_free_on_drop();
        let upwqp = upwqp.ptr;
        let mut context = context;
        context.do_not_free_on_drop();
        let context = context.ptr;
        let isl_rs_result = unsafe { isl_union_pw_qpolynomial_gist_params(upwqp, context) };
        let isl_rs_result = UnionPwQPolynomial { ptr: isl_rs_result,
                                                 should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_intersect_domain`.
    pub fn intersect_domain(self, uset: UnionSet) -> Result<UnionPwQPolynomial, LibISLError> {
        let upwpq = self;
        let isl_rs_ctx = upwpq.get_ctx();
        let mut upwpq = upwpq;
        upwpq.do_not_free_on_drop();
        let upwpq = upwpq.ptr;
        let mut uset = uset;
        uset.do_not_free_on_drop();
        let uset = uset.ptr;
        let isl_rs_result = unsafe { isl_union_pw_qpolynomial_intersect_domain(upwpq, uset) };
        let isl_rs_result = UnionPwQPolynomial { ptr: isl_rs_result,
                                                 should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_intersect_domain_space`.
    pub fn intersect_domain_space(self, space: Space) -> Result<UnionPwQPolynomial, LibISLError> {
        let upwpq = self;
        let isl_rs_ctx = upwpq.get_ctx();
        let mut upwpq = upwpq;
        upwpq.do_not_free_on_drop();
        let upwpq = upwpq.ptr;
        let mut space = space;
        space.do_not_free_on_drop();
        let space = space.ptr;
        let isl_rs_result =
            unsafe { isl_union_pw_qpolynomial_intersect_domain_space(upwpq, space) };
        let isl_rs_result = UnionPwQPolynomial { ptr: isl_rs_result,
                                                 should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_intersect_domain_union_set`.
    pub fn intersect_domain_union_set(self, uset: UnionSet)
                                      -> Result<UnionPwQPolynomial, LibISLError> {
        let upwpq = self;
        let isl_rs_ctx = upwpq.get_ctx();
        let mut upwpq = upwpq;
        upwpq.do_not_free_on_drop();
        let upwpq = upwpq.ptr;
        let mut uset = uset;
        uset.do_not_free_on_drop();
        let uset = uset.ptr;
        let isl_rs_result =
            unsafe { isl_union_pw_qpolynomial_intersect_domain_union_set(upwpq, uset) };
        let isl_rs_result = UnionPwQPolynomial { ptr: isl_rs_result,
                                                 should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_intersect_domain_wrapped_domain`.
    pub fn intersect_domain_wrapped_domain(self, uset: UnionSet)
                                           -> Result<UnionPwQPolynomial, LibISLError> {
        let upwpq = self;
        let isl_rs_ctx = upwpq.get_ctx();
        let mut upwpq = upwpq;
        upwpq.do_not_free_on_drop();
        let upwpq = upwpq.ptr;
        let mut uset = uset;
        uset.do_not_free_on_drop();
        let uset = uset.ptr;
        let isl_rs_result =
            unsafe { isl_union_pw_qpolynomial_intersect_domain_wrapped_domain(upwpq, uset) };
        let isl_rs_result = UnionPwQPolynomial { ptr: isl_rs_result,
                                                 should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_intersect_domain_wrapped_range`.
    pub fn intersect_domain_wrapped_range(self, uset: UnionSet)
                                          -> Result<UnionPwQPolynomial, LibISLError> {
        let upwpq = self;
        let isl_rs_ctx = upwpq.get_ctx();
        let mut upwpq = upwpq;
        upwpq.do_not_free_on_drop();
        let upwpq = upwpq.ptr;
        let mut uset = uset;
        uset.do_not_free_on_drop();
        let uset = uset.ptr;
        let isl_rs_result =
            unsafe { isl_union_pw_qpolynomial_intersect_domain_wrapped_range(upwpq, uset) };
        let isl_rs_result = UnionPwQPolynomial { ptr: isl_rs_result,
                                                 should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_intersect_params`.
    pub fn intersect_params(self, set: Set) -> Result<UnionPwQPolynomial, LibISLError> {
        let upwpq = self;
        let isl_rs_ctx = upwpq.get_ctx();
        let mut upwpq = upwpq;
        upwpq.do_not_free_on_drop();
        let upwpq = upwpq.ptr;
        let mut set = set;
        set.do_not_free_on_drop();
        let set = set.ptr;
        let isl_rs_result = unsafe { isl_union_pw_qpolynomial_intersect_params(upwpq, set) };
        let isl_rs_result = UnionPwQPolynomial { ptr: isl_rs_result,
                                                 should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_involves_nan`.
    pub fn involves_nan(&self) -> Result<bool, LibISLError> {
        let upwqp = self;
        let isl_rs_ctx = upwqp.get_ctx();
        let upwqp = upwqp.ptr;
        let isl_rs_result = unsafe { isl_union_pw_qpolynomial_involves_nan(upwqp) };
        let isl_rs_result = match isl_rs_result {
            0 => false,
            1 => true,
            _ => panic!("Got isl_bool = -1"),
        };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_mul`.
    pub fn mul(self, upwqp2: UnionPwQPolynomial) -> Result<UnionPwQPolynomial, LibISLError> {
        let upwqp1 = self;
        let isl_rs_ctx = upwqp1.get_ctx();
        let mut upwqp1 = upwqp1;
        upwqp1.do_not_free_on_drop();
        let upwqp1 = upwqp1.ptr;
        let mut upwqp2 = upwqp2;
        upwqp2.do_not_free_on_drop();
        let upwqp2 = upwqp2.ptr;
        let isl_rs_result = unsafe { isl_union_pw_qpolynomial_mul(upwqp1, upwqp2) };
        let isl_rs_result = UnionPwQPolynomial { ptr: isl_rs_result,
                                                 should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_n_pw_qpolynomial`.
    pub fn n_pw_qpolynomial(&self) -> Result<i32, LibISLError> {
        let upwqp = self;
        let isl_rs_ctx = upwqp.get_ctx();
        let upwqp = upwqp.ptr;
        let isl_rs_result = unsafe { isl_union_pw_qpolynomial_n_pw_qpolynomial(upwqp) };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_neg`.
    pub fn neg(self) -> Result<UnionPwQPolynomial, LibISLError> {
        let upwqp = self;
        let isl_rs_ctx = upwqp.get_ctx();
        let mut upwqp = upwqp;
        upwqp.do_not_free_on_drop();
        let upwqp = upwqp.ptr;
        let isl_rs_result = unsafe { isl_union_pw_qpolynomial_neg(upwqp) };
        let isl_rs_result = UnionPwQPolynomial { ptr: isl_rs_result,
                                                 should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_plain_is_equal`.
    pub fn plain_is_equal(&self, upwqp2: &UnionPwQPolynomial) -> Result<bool, LibISLError> {
        let upwqp1 = self;
        let isl_rs_ctx = upwqp1.get_ctx();
        let upwqp1 = upwqp1.ptr;
        let upwqp2 = upwqp2.ptr;
        let isl_rs_result = unsafe { isl_union_pw_qpolynomial_plain_is_equal(upwqp1, upwqp2) };
        let isl_rs_result = match isl_rs_result {
            0 => false,
            1 => true,
            _ => panic!("Got isl_bool = -1"),
        };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_read_from_str`.
    pub fn read_from_str(ctx: &Context, str_: &str) -> Result<UnionPwQPolynomial, LibISLError> {
        let isl_rs_ctx = Context { ptr: ctx.ptr,
                                   should_free_on_drop: false };
        let ctx = ctx.ptr;
        let str_ = CString::new(str_).unwrap();
        let str_ = str_.as_ptr();
        let isl_rs_result = unsafe { isl_union_pw_qpolynomial_read_from_str(ctx, str_) };
        let isl_rs_result = UnionPwQPolynomial { ptr: isl_rs_result,
                                                 should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_reset_user`.
    pub fn reset_user(self) -> Result<UnionPwQPolynomial, LibISLError> {
        let upwqp = self;
        let isl_rs_ctx = upwqp.get_ctx();
        let mut upwqp = upwqp;
        upwqp.do_not_free_on_drop();
        let upwqp = upwqp.ptr;
        let isl_rs_result = unsafe { isl_union_pw_qpolynomial_reset_user(upwqp) };
        let isl_rs_result = UnionPwQPolynomial { ptr: isl_rs_result,
                                                 should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_scale_down_val`.
    pub fn scale_down_val(self, v: Val) -> Result<UnionPwQPolynomial, LibISLError> {
        let upwqp = self;
        let isl_rs_ctx = upwqp.get_ctx();
        let mut upwqp = upwqp;
        upwqp.do_not_free_on_drop();
        let upwqp = upwqp.ptr;
        let mut v = v;
        v.do_not_free_on_drop();
        let v = v.ptr;
        let isl_rs_result = unsafe { isl_union_pw_qpolynomial_scale_down_val(upwqp, v) };
        let isl_rs_result = UnionPwQPolynomial { ptr: isl_rs_result,
                                                 should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_scale_val`.
    pub fn scale_val(self, v: Val) -> Result<UnionPwQPolynomial, LibISLError> {
        let upwqp = self;
        let isl_rs_ctx = upwqp.get_ctx();
        let mut upwqp = upwqp;
        upwqp.do_not_free_on_drop();
        let upwqp = upwqp.ptr;
        let mut v = v;
        v.do_not_free_on_drop();
        let v = v.ptr;
        let isl_rs_result = unsafe { isl_union_pw_qpolynomial_scale_val(upwqp, v) };
        let isl_rs_result = UnionPwQPolynomial { ptr: isl_rs_result,
                                                 should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_set_dim_name`.
    pub fn set_dim_name(self, type_: DimType, pos: u32, s: &str)
                        -> Result<UnionPwQPolynomial, LibISLError> {
        let upwqp = self;
        let isl_rs_ctx = upwqp.get_ctx();
        let mut upwqp = upwqp;
        upwqp.do_not_free_on_drop();
        let upwqp = upwqp.ptr;
        let type_ = type_.to_i32();
        let s = CString::new(s).unwrap();
        let s = s.as_ptr();
        let isl_rs_result = unsafe { isl_union_pw_qpolynomial_set_dim_name(upwqp, type_, pos, s) };
        let isl_rs_result = UnionPwQPolynomial { ptr: isl_rs_result,
                                                 should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_sub`.
    pub fn sub(self, upwqp2: UnionPwQPolynomial) -> Result<UnionPwQPolynomial, LibISLError> {
        let upwqp1 = self;
        let isl_rs_ctx = upwqp1.get_ctx();
        let mut upwqp1 = upwqp1;
        upwqp1.do_not_free_on_drop();
        let upwqp1 = upwqp1.ptr;
        let mut upwqp2 = upwqp2;
        upwqp2.do_not_free_on_drop();
        let upwqp2 = upwqp2.ptr;
        let isl_rs_result = unsafe { isl_union_pw_qpolynomial_sub(upwqp1, upwqp2) };
        let isl_rs_result = UnionPwQPolynomial { ptr: isl_rs_result,
                                                 should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_subtract_domain`.
    pub fn subtract_domain(self, uset: UnionSet) -> Result<UnionPwQPolynomial, LibISLError> {
        let upwpq = self;
        let isl_rs_ctx = upwpq.get_ctx();
        let mut upwpq = upwpq;
        upwpq.do_not_free_on_drop();
        let upwpq = upwpq.ptr;
        let mut uset = uset;
        uset.do_not_free_on_drop();
        let uset = uset.ptr;
        let isl_rs_result = unsafe { isl_union_pw_qpolynomial_subtract_domain(upwpq, uset) };
        let isl_rs_result = UnionPwQPolynomial { ptr: isl_rs_result,
                                                 should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_subtract_domain_space`.
    pub fn subtract_domain_space(self, space: Space) -> Result<UnionPwQPolynomial, LibISLError> {
        let upwpq = self;
        let isl_rs_ctx = upwpq.get_ctx();
        let mut upwpq = upwpq;
        upwpq.do_not_free_on_drop();
        let upwpq = upwpq.ptr;
        let mut space = space;
        space.do_not_free_on_drop();
        let space = space.ptr;
        let isl_rs_result = unsafe { isl_union_pw_qpolynomial_subtract_domain_space(upwpq, space) };
        let isl_rs_result = UnionPwQPolynomial { ptr: isl_rs_result,
                                                 should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_subtract_domain_union_set`.
    pub fn subtract_domain_union_set(self, uset: UnionSet)
                                     -> Result<UnionPwQPolynomial, LibISLError> {
        let upwpq = self;
        let isl_rs_ctx = upwpq.get_ctx();
        let mut upwpq = upwpq;
        upwpq.do_not_free_on_drop();
        let upwpq = upwpq.ptr;
        let mut uset = uset;
        uset.do_not_free_on_drop();
        let uset = uset.ptr;
        let isl_rs_result =
            unsafe { isl_union_pw_qpolynomial_subtract_domain_union_set(upwpq, uset) };
        let isl_rs_result = UnionPwQPolynomial { ptr: isl_rs_result,
                                                 should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_to_polynomial`.
    pub fn to_polynomial(self, sign: i32) -> Result<UnionPwQPolynomial, LibISLError> {
        let upwqp = self;
        let isl_rs_ctx = upwqp.get_ctx();
        let mut upwqp = upwqp;
        upwqp.do_not_free_on_drop();
        let upwqp = upwqp.ptr;
        let isl_rs_result = unsafe { isl_union_pw_qpolynomial_to_polynomial(upwqp, sign) };
        let isl_rs_result = UnionPwQPolynomial { ptr: isl_rs_result,
                                                 should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_to_str`.
    pub fn to_str(&self) -> Result<&str, LibISLError> {
        let upwqp = self;
        let isl_rs_ctx = upwqp.get_ctx();
        let upwqp = upwqp.ptr;
        let isl_rs_result = unsafe { isl_union_pw_qpolynomial_to_str(upwqp) };
        let isl_rs_result = unsafe { CStr::from_ptr(isl_rs_result) };
        let isl_rs_result = isl_rs_result.to_str().unwrap();
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_zero`.
    pub fn zero(space: Space) -> Result<UnionPwQPolynomial, LibISLError> {
        let isl_rs_ctx = space.get_ctx();
        let mut space = space;
        space.do_not_free_on_drop();
        let space = space.ptr;
        let isl_rs_result = unsafe { isl_union_pw_qpolynomial_zero(space) };
        let isl_rs_result = UnionPwQPolynomial { ptr: isl_rs_result,
                                                 should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_zero_ctx`.
    pub fn zero_ctx(ctx: &Context) -> Result<UnionPwQPolynomial, LibISLError> {
        let isl_rs_ctx = Context { ptr: ctx.ptr,
                                   should_free_on_drop: false };
        let ctx = ctx.ptr;
        let isl_rs_result = unsafe { isl_union_pw_qpolynomial_zero_ctx(ctx) };
        let isl_rs_result = UnionPwQPolynomial { ptr: isl_rs_result,
                                                 should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_qpolynomial_zero_space`.
    pub fn zero_space(space: Space) -> Result<UnionPwQPolynomial, LibISLError> {
        let isl_rs_ctx = space.get_ctx();
        let mut space = space;
        space.do_not_free_on_drop();
        let space = space.ptr;
        let isl_rs_result = unsafe { isl_union_pw_qpolynomial_zero_space(space) };
        let isl_rs_result = UnionPwQPolynomial { ptr: isl_rs_result,
                                                 should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Does not call isl_union_pw_qpolynomial_free() on being dropped. (For
    /// internal use only.)
    pub fn do_not_free_on_drop(&mut self) {
        self.should_free_on_drop = false;
    }
}

impl Drop for UnionPwQPolynomial {
    fn drop(&mut self) {
        if self.should_free_on_drop {
            unsafe {
                isl_union_pw_qpolynomial_free(self.ptr);
            }
        }
    }
}
