// Automatically generated by isl_bindings_generator.
// LICENSE: MIT

use super::{
    Aff, Context, DimType, Error, LibISLError, MultiAff, MultiUnionPwAff, MultiVal, PwMultiAff,
    PwMultiAffList, Set, Space, UnionMap, UnionPwAff, UnionPwMultiAffList, UnionSet, Val,
};
use libc::uintptr_t;
use std::ffi::{CStr, CString};
use std::os::raw::c_char;

/// Wraps `isl_union_pw_multi_aff`.
pub struct UnionPwMultiAff {
    pub ptr: uintptr_t,
    pub should_free_on_drop: bool,
}

extern "C" {

    fn isl_union_pw_multi_aff_add(upma1: uintptr_t, upma2: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_add_pw_multi_aff(upma: uintptr_t, pma: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_align_params(upma: uintptr_t, model: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_apply_union_pw_multi_aff(upma1: uintptr_t, upma2: uintptr_t)
                                                       -> uintptr_t;

    fn isl_union_pw_multi_aff_as_multi_union_pw_aff(upma: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_as_pw_multi_aff(upma: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_as_union_map(upma: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_coalesce(upma: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_copy(upma: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_dim(upma: uintptr_t, type_: i32) -> i32;

    fn isl_union_pw_multi_aff_domain(upma: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_drop_dims(upma: uintptr_t, type_: i32, first: u32, n: u32)
                                        -> uintptr_t;

    fn isl_union_pw_multi_aff_drop_unused_params(upma: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_dump(upma: uintptr_t) -> ();

    fn isl_union_pw_multi_aff_empty(space: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_empty_ctx(ctx: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_empty_space(space: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_extract_pw_multi_aff(upma: uintptr_t, space: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_find_dim_by_name(upma: uintptr_t, type_: i32, name: *const c_char)
                                               -> i32;

    fn isl_union_pw_multi_aff_flat_range_product(upma1: uintptr_t, upma2: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_free(upma: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_from_aff(aff: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_from_domain(uset: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_from_multi_aff(ma: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_from_multi_union_pw_aff(mupa: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_from_pw_multi_aff(pma: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_from_union_map(umap: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_from_union_pw_aff(upa: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_from_union_set(uset: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_get_ctx(upma: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_get_pw_multi_aff_list(upma: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_get_space(upma: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_get_union_pw_aff(upma: uintptr_t, pos: i32) -> uintptr_t;

    fn isl_union_pw_multi_aff_gist(upma: uintptr_t, context: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_gist_params(upma: uintptr_t, context: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_intersect_domain(upma: uintptr_t, uset: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_intersect_domain_space(upma: uintptr_t, space: uintptr_t)
                                                     -> uintptr_t;

    fn isl_union_pw_multi_aff_intersect_domain_union_set(upma: uintptr_t, uset: uintptr_t)
                                                         -> uintptr_t;

    fn isl_union_pw_multi_aff_intersect_domain_wrapped_domain(upma: uintptr_t, uset: uintptr_t)
                                                              -> uintptr_t;

    fn isl_union_pw_multi_aff_intersect_domain_wrapped_range(upma: uintptr_t, uset: uintptr_t)
                                                             -> uintptr_t;

    fn isl_union_pw_multi_aff_intersect_params(upma: uintptr_t, set: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_involves_locals(upma: uintptr_t) -> i32;

    fn isl_union_pw_multi_aff_involves_nan(upma: uintptr_t) -> i32;

    fn isl_union_pw_multi_aff_isa_pw_multi_aff(upma: uintptr_t) -> i32;

    fn isl_union_pw_multi_aff_multi_val_on_domain(domain: uintptr_t, mv: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_n_pw_multi_aff(upma: uintptr_t) -> i32;

    fn isl_union_pw_multi_aff_neg(upma: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_plain_is_empty(upma: uintptr_t) -> i32;

    fn isl_union_pw_multi_aff_plain_is_equal(upma1: uintptr_t, upma2: uintptr_t) -> i32;

    fn isl_union_pw_multi_aff_preimage_domain_wrapped_domain_union_pw_multi_aff(upma1: uintptr_t,
                                                                                upma2: uintptr_t)
                                                                                -> uintptr_t;

    fn isl_union_pw_multi_aff_pullback_union_pw_multi_aff(upma1: uintptr_t, upma2: uintptr_t)
                                                          -> uintptr_t;

    fn isl_union_pw_multi_aff_range_factor_domain(upma: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_range_factor_range(upma: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_range_product(upma1: uintptr_t, upma2: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_read_from_str(ctx: uintptr_t, str_: *const c_char) -> uintptr_t;

    fn isl_union_pw_multi_aff_reset_user(upma: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_scale_down_val(upma: uintptr_t, val: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_scale_multi_val(upma: uintptr_t, mv: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_scale_val(upma: uintptr_t, val: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_set_dim_name(upma: uintptr_t, type_: i32, pos: u32, s: *const c_char)
                                           -> uintptr_t;

    fn isl_union_pw_multi_aff_sub(upma1: uintptr_t, upma2: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_subtract_domain(upma: uintptr_t, uset: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_subtract_domain_space(upma: uintptr_t, space: uintptr_t)
                                                    -> uintptr_t;

    fn isl_union_pw_multi_aff_subtract_domain_union_set(upma: uintptr_t, uset: uintptr_t)
                                                        -> uintptr_t;

    fn isl_union_pw_multi_aff_to_list(el: uintptr_t) -> uintptr_t;

    fn isl_union_pw_multi_aff_to_str(upma: uintptr_t) -> *const c_char;

    fn isl_union_pw_multi_aff_union_add(upma1: uintptr_t, upma2: uintptr_t) -> uintptr_t;

}

impl UnionPwMultiAff {
    /// Wraps `isl_union_pw_multi_aff_add`.
    pub fn add(self, upma2: UnionPwMultiAff) -> Result<UnionPwMultiAff, LibISLError> {
        let upma1 = self;
        let isl_rs_ctx = upma1.get_ctx();
        let mut upma1 = upma1;
        upma1.do_not_free_on_drop();
        let upma1 = upma1.ptr;
        let mut upma2 = upma2;
        upma2.do_not_free_on_drop();
        let upma2 = upma2.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_add(upma1, upma2) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_add_pw_multi_aff`.
    pub fn add_pw_multi_aff(self, pma: PwMultiAff) -> Result<UnionPwMultiAff, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let mut upma = upma;
        upma.do_not_free_on_drop();
        let upma = upma.ptr;
        let mut pma = pma;
        pma.do_not_free_on_drop();
        let pma = pma.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_add_pw_multi_aff(upma, pma) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_align_params`.
    pub fn align_params(self, model: Space) -> Result<UnionPwMultiAff, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let mut upma = upma;
        upma.do_not_free_on_drop();
        let upma = upma.ptr;
        let mut model = model;
        model.do_not_free_on_drop();
        let model = model.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_align_params(upma, model) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_apply_union_pw_multi_aff`.
    pub fn apply_union_pw_multi_aff(self, upma2: UnionPwMultiAff)
                                    -> Result<UnionPwMultiAff, LibISLError> {
        let upma1 = self;
        let isl_rs_ctx = upma1.get_ctx();
        let mut upma1 = upma1;
        upma1.do_not_free_on_drop();
        let upma1 = upma1.ptr;
        let mut upma2 = upma2;
        upma2.do_not_free_on_drop();
        let upma2 = upma2.ptr;
        let isl_rs_result =
            unsafe { isl_union_pw_multi_aff_apply_union_pw_multi_aff(upma1, upma2) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_as_multi_union_pw_aff`.
    pub fn as_multi_union_pw_aff(self) -> Result<MultiUnionPwAff, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let mut upma = upma;
        upma.do_not_free_on_drop();
        let upma = upma.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_as_multi_union_pw_aff(upma) };
        let isl_rs_result = MultiUnionPwAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_as_pw_multi_aff`.
    pub fn as_pw_multi_aff(self) -> Result<PwMultiAff, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let mut upma = upma;
        upma.do_not_free_on_drop();
        let upma = upma.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_as_pw_multi_aff(upma) };
        let isl_rs_result = PwMultiAff { ptr: isl_rs_result,
                                         should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_as_union_map`.
    pub fn as_union_map(self) -> Result<UnionMap, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let mut upma = upma;
        upma.do_not_free_on_drop();
        let upma = upma.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_as_union_map(upma) };
        let isl_rs_result = UnionMap { ptr: isl_rs_result,
                                       should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_coalesce`.
    pub fn coalesce(self) -> Result<UnionPwMultiAff, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let mut upma = upma;
        upma.do_not_free_on_drop();
        let upma = upma.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_coalesce(upma) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_copy`.
    pub fn copy(&self) -> Result<UnionPwMultiAff, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let upma = upma.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_copy(upma) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_dim`.
    pub fn dim(&self, type_: DimType) -> Result<i32, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let upma = upma.ptr;
        let type_ = type_.to_i32();
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_dim(upma, type_) };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_domain`.
    pub fn domain(self) -> Result<UnionSet, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let mut upma = upma;
        upma.do_not_free_on_drop();
        let upma = upma.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_domain(upma) };
        let isl_rs_result = UnionSet { ptr: isl_rs_result,
                                       should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_drop_dims`.
    pub fn drop_dims(self, type_: DimType, first: u32, n: u32)
                     -> Result<UnionPwMultiAff, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let mut upma = upma;
        upma.do_not_free_on_drop();
        let upma = upma.ptr;
        let type_ = type_.to_i32();
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_drop_dims(upma, type_, first, n) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_drop_unused_params`.
    pub fn drop_unused_params(self) -> Result<UnionPwMultiAff, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let mut upma = upma;
        upma.do_not_free_on_drop();
        let upma = upma.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_drop_unused_params(upma) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_dump`.
    pub fn dump(&self) -> Result<(), LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let upma = upma.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_dump(upma) };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_empty`.
    pub fn empty(space: Space) -> Result<UnionPwMultiAff, LibISLError> {
        let isl_rs_ctx = space.get_ctx();
        let mut space = space;
        space.do_not_free_on_drop();
        let space = space.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_empty(space) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_empty_ctx`.
    pub fn empty_ctx(ctx: &Context) -> Result<UnionPwMultiAff, LibISLError> {
        let isl_rs_ctx = Context { ptr: ctx.ptr,
                                   should_free_on_drop: false };
        let ctx = ctx.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_empty_ctx(ctx) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_empty_space`.
    pub fn empty_space(space: Space) -> Result<UnionPwMultiAff, LibISLError> {
        let isl_rs_ctx = space.get_ctx();
        let mut space = space;
        space.do_not_free_on_drop();
        let space = space.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_empty_space(space) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_extract_pw_multi_aff`.
    pub fn extract_pw_multi_aff(&self, space: Space) -> Result<PwMultiAff, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let upma = upma.ptr;
        let mut space = space;
        space.do_not_free_on_drop();
        let space = space.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_extract_pw_multi_aff(upma, space) };
        let isl_rs_result = PwMultiAff { ptr: isl_rs_result,
                                         should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_find_dim_by_name`.
    pub fn find_dim_by_name(&self, type_: DimType, name: &str) -> Result<i32, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let upma = upma.ptr;
        let type_ = type_.to_i32();
        let name = CString::new(name).unwrap();
        let name = name.as_ptr();
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_find_dim_by_name(upma, type_, name) };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_flat_range_product`.
    pub fn flat_range_product(self, upma2: UnionPwMultiAff)
                              -> Result<UnionPwMultiAff, LibISLError> {
        let upma1 = self;
        let isl_rs_ctx = upma1.get_ctx();
        let mut upma1 = upma1;
        upma1.do_not_free_on_drop();
        let upma1 = upma1.ptr;
        let mut upma2 = upma2;
        upma2.do_not_free_on_drop();
        let upma2 = upma2.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_flat_range_product(upma1, upma2) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_free`.
    pub fn free(self) -> Result<UnionPwMultiAff, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let mut upma = upma;
        upma.do_not_free_on_drop();
        let upma = upma.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_free(upma) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_from_aff`.
    pub fn from_aff(aff: Aff) -> Result<UnionPwMultiAff, LibISLError> {
        let isl_rs_ctx = aff.get_ctx();
        let mut aff = aff;
        aff.do_not_free_on_drop();
        let aff = aff.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_from_aff(aff) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_from_domain`.
    pub fn from_domain(uset: UnionSet) -> Result<UnionPwMultiAff, LibISLError> {
        let isl_rs_ctx = uset.get_ctx();
        let mut uset = uset;
        uset.do_not_free_on_drop();
        let uset = uset.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_from_domain(uset) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_from_multi_aff`.
    pub fn from_multi_aff(ma: MultiAff) -> Result<UnionPwMultiAff, LibISLError> {
        let isl_rs_ctx = ma.get_ctx();
        let mut ma = ma;
        ma.do_not_free_on_drop();
        let ma = ma.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_from_multi_aff(ma) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_from_multi_union_pw_aff`.
    pub fn from_multi_union_pw_aff(mupa: MultiUnionPwAff) -> Result<UnionPwMultiAff, LibISLError> {
        let isl_rs_ctx = mupa.get_ctx();
        let mut mupa = mupa;
        mupa.do_not_free_on_drop();
        let mupa = mupa.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_from_multi_union_pw_aff(mupa) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_from_pw_multi_aff`.
    pub fn from_pw_multi_aff(pma: PwMultiAff) -> Result<UnionPwMultiAff, LibISLError> {
        let isl_rs_ctx = pma.get_ctx();
        let mut pma = pma;
        pma.do_not_free_on_drop();
        let pma = pma.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_from_pw_multi_aff(pma) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_from_union_map`.
    pub fn from_union_map(umap: UnionMap) -> Result<UnionPwMultiAff, LibISLError> {
        let isl_rs_ctx = umap.get_ctx();
        let mut umap = umap;
        umap.do_not_free_on_drop();
        let umap = umap.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_from_union_map(umap) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_from_union_pw_aff`.
    pub fn from_union_pw_aff(upa: UnionPwAff) -> Result<UnionPwMultiAff, LibISLError> {
        let isl_rs_ctx = upa.get_ctx();
        let mut upa = upa;
        upa.do_not_free_on_drop();
        let upa = upa.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_from_union_pw_aff(upa) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_from_union_set`.
    pub fn from_union_set(uset: UnionSet) -> Result<UnionPwMultiAff, LibISLError> {
        let isl_rs_ctx = uset.get_ctx();
        let mut uset = uset;
        uset.do_not_free_on_drop();
        let uset = uset.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_from_union_set(uset) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_get_ctx`.
    pub fn get_ctx(&self) -> Context {
        let upma = self;
        let upma = upma.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_get_ctx(upma) };
        let isl_rs_result = Context { ptr: isl_rs_result,
                                      should_free_on_drop: false };
        isl_rs_result
    }

    /// Wraps `isl_union_pw_multi_aff_get_pw_multi_aff_list`.
    pub fn get_pw_multi_aff_list(&self) -> Result<PwMultiAffList, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let upma = upma.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_get_pw_multi_aff_list(upma) };
        let isl_rs_result = PwMultiAffList { ptr: isl_rs_result,
                                             should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_get_space`.
    pub fn get_space(&self) -> Result<Space, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let upma = upma.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_get_space(upma) };
        let isl_rs_result = Space { ptr: isl_rs_result,
                                    should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_get_union_pw_aff`.
    pub fn get_union_pw_aff(&self, pos: i32) -> Result<UnionPwAff, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let upma = upma.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_get_union_pw_aff(upma, pos) };
        let isl_rs_result = UnionPwAff { ptr: isl_rs_result,
                                         should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_gist`.
    pub fn gist(self, context: UnionSet) -> Result<UnionPwMultiAff, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let mut upma = upma;
        upma.do_not_free_on_drop();
        let upma = upma.ptr;
        let mut context = context;
        context.do_not_free_on_drop();
        let context = context.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_gist(upma, context) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_gist_params`.
    pub fn gist_params(self, context: Set) -> Result<UnionPwMultiAff, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let mut upma = upma;
        upma.do_not_free_on_drop();
        let upma = upma.ptr;
        let mut context = context;
        context.do_not_free_on_drop();
        let context = context.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_gist_params(upma, context) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_intersect_domain`.
    pub fn intersect_domain(self, uset: UnionSet) -> Result<UnionPwMultiAff, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let mut upma = upma;
        upma.do_not_free_on_drop();
        let upma = upma.ptr;
        let mut uset = uset;
        uset.do_not_free_on_drop();
        let uset = uset.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_intersect_domain(upma, uset) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_intersect_domain_space`.
    pub fn intersect_domain_space(self, space: Space) -> Result<UnionPwMultiAff, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let mut upma = upma;
        upma.do_not_free_on_drop();
        let upma = upma.ptr;
        let mut space = space;
        space.do_not_free_on_drop();
        let space = space.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_intersect_domain_space(upma, space) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_intersect_domain_union_set`.
    pub fn intersect_domain_union_set(self, uset: UnionSet)
                                      -> Result<UnionPwMultiAff, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let mut upma = upma;
        upma.do_not_free_on_drop();
        let upma = upma.ptr;
        let mut uset = uset;
        uset.do_not_free_on_drop();
        let uset = uset.ptr;
        let isl_rs_result =
            unsafe { isl_union_pw_multi_aff_intersect_domain_union_set(upma, uset) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_intersect_domain_wrapped_domain`.
    pub fn intersect_domain_wrapped_domain(self, uset: UnionSet)
                                           -> Result<UnionPwMultiAff, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let mut upma = upma;
        upma.do_not_free_on_drop();
        let upma = upma.ptr;
        let mut uset = uset;
        uset.do_not_free_on_drop();
        let uset = uset.ptr;
        let isl_rs_result =
            unsafe { isl_union_pw_multi_aff_intersect_domain_wrapped_domain(upma, uset) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_intersect_domain_wrapped_range`.
    pub fn intersect_domain_wrapped_range(self, uset: UnionSet)
                                          -> Result<UnionPwMultiAff, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let mut upma = upma;
        upma.do_not_free_on_drop();
        let upma = upma.ptr;
        let mut uset = uset;
        uset.do_not_free_on_drop();
        let uset = uset.ptr;
        let isl_rs_result =
            unsafe { isl_union_pw_multi_aff_intersect_domain_wrapped_range(upma, uset) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_intersect_params`.
    pub fn intersect_params(self, set: Set) -> Result<UnionPwMultiAff, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let mut upma = upma;
        upma.do_not_free_on_drop();
        let upma = upma.ptr;
        let mut set = set;
        set.do_not_free_on_drop();
        let set = set.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_intersect_params(upma, set) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_involves_locals`.
    pub fn involves_locals(&self) -> Result<bool, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let upma = upma.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_involves_locals(upma) };
        let isl_rs_result = match isl_rs_result {
            0 => false,
            1 => true,
            _ => panic!("Got isl_bool = -1"),
        };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_involves_nan`.
    pub fn involves_nan(&self) -> Result<bool, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let upma = upma.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_involves_nan(upma) };
        let isl_rs_result = match isl_rs_result {
            0 => false,
            1 => true,
            _ => panic!("Got isl_bool = -1"),
        };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_isa_pw_multi_aff`.
    pub fn isa_pw_multi_aff(&self) -> Result<bool, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let upma = upma.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_isa_pw_multi_aff(upma) };
        let isl_rs_result = match isl_rs_result {
            0 => false,
            1 => true,
            _ => panic!("Got isl_bool = -1"),
        };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_multi_val_on_domain`.
    pub fn multi_val_on_domain(domain: UnionSet, mv: MultiVal)
                               -> Result<UnionPwMultiAff, LibISLError> {
        let isl_rs_ctx = domain.get_ctx();
        let mut domain = domain;
        domain.do_not_free_on_drop();
        let domain = domain.ptr;
        let mut mv = mv;
        mv.do_not_free_on_drop();
        let mv = mv.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_multi_val_on_domain(domain, mv) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_n_pw_multi_aff`.
    pub fn n_pw_multi_aff(&self) -> Result<i32, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let upma = upma.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_n_pw_multi_aff(upma) };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_neg`.
    pub fn neg(self) -> Result<UnionPwMultiAff, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let mut upma = upma;
        upma.do_not_free_on_drop();
        let upma = upma.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_neg(upma) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_plain_is_empty`.
    pub fn plain_is_empty(&self) -> Result<bool, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let upma = upma.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_plain_is_empty(upma) };
        let isl_rs_result = match isl_rs_result {
            0 => false,
            1 => true,
            _ => panic!("Got isl_bool = -1"),
        };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_plain_is_equal`.
    pub fn plain_is_equal(&self, upma2: &UnionPwMultiAff) -> Result<bool, LibISLError> {
        let upma1 = self;
        let isl_rs_ctx = upma1.get_ctx();
        let upma1 = upma1.ptr;
        let upma2 = upma2.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_plain_is_equal(upma1, upma2) };
        let isl_rs_result = match isl_rs_result {
            0 => false,
            1 => true,
            _ => panic!("Got isl_bool = -1"),
        };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_preimage_domain_wrapped_domain_union_pw_multi_aff`.
    pub fn preimage_domain_wrapped_domain_union_pw_multi_aff(
        self, upma2: UnionPwMultiAff)
        -> Result<UnionPwMultiAff, LibISLError> {
        let upma1 = self;
        let isl_rs_ctx = upma1.get_ctx();
        let mut upma1 = upma1;
        upma1.do_not_free_on_drop();
        let upma1 = upma1.ptr;
        let mut upma2 = upma2;
        upma2.do_not_free_on_drop();
        let upma2 = upma2.ptr;
        let isl_rs_result = unsafe {
            isl_union_pw_multi_aff_preimage_domain_wrapped_domain_union_pw_multi_aff(upma1, upma2)
        };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_pullback_union_pw_multi_aff`.
    pub fn pullback_union_pw_multi_aff(self, upma2: UnionPwMultiAff)
                                       -> Result<UnionPwMultiAff, LibISLError> {
        let upma1 = self;
        let isl_rs_ctx = upma1.get_ctx();
        let mut upma1 = upma1;
        upma1.do_not_free_on_drop();
        let upma1 = upma1.ptr;
        let mut upma2 = upma2;
        upma2.do_not_free_on_drop();
        let upma2 = upma2.ptr;
        let isl_rs_result =
            unsafe { isl_union_pw_multi_aff_pullback_union_pw_multi_aff(upma1, upma2) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_range_factor_domain`.
    pub fn range_factor_domain(self) -> Result<UnionPwMultiAff, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let mut upma = upma;
        upma.do_not_free_on_drop();
        let upma = upma.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_range_factor_domain(upma) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_range_factor_range`.
    pub fn range_factor_range(self) -> Result<UnionPwMultiAff, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let mut upma = upma;
        upma.do_not_free_on_drop();
        let upma = upma.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_range_factor_range(upma) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_range_product`.
    pub fn range_product(self, upma2: UnionPwMultiAff) -> Result<UnionPwMultiAff, LibISLError> {
        let upma1 = self;
        let isl_rs_ctx = upma1.get_ctx();
        let mut upma1 = upma1;
        upma1.do_not_free_on_drop();
        let upma1 = upma1.ptr;
        let mut upma2 = upma2;
        upma2.do_not_free_on_drop();
        let upma2 = upma2.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_range_product(upma1, upma2) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_read_from_str`.
    pub fn read_from_str(ctx: &Context, str_: &str) -> Result<UnionPwMultiAff, LibISLError> {
        let isl_rs_ctx = Context { ptr: ctx.ptr,
                                   should_free_on_drop: false };
        let ctx = ctx.ptr;
        let str_ = CString::new(str_).unwrap();
        let str_ = str_.as_ptr();
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_read_from_str(ctx, str_) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_reset_user`.
    pub fn reset_user(self) -> Result<UnionPwMultiAff, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let mut upma = upma;
        upma.do_not_free_on_drop();
        let upma = upma.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_reset_user(upma) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_scale_down_val`.
    pub fn scale_down_val(self, val: Val) -> Result<UnionPwMultiAff, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let mut upma = upma;
        upma.do_not_free_on_drop();
        let upma = upma.ptr;
        let mut val = val;
        val.do_not_free_on_drop();
        let val = val.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_scale_down_val(upma, val) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_scale_multi_val`.
    pub fn scale_multi_val(self, mv: MultiVal) -> Result<UnionPwMultiAff, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let mut upma = upma;
        upma.do_not_free_on_drop();
        let upma = upma.ptr;
        let mut mv = mv;
        mv.do_not_free_on_drop();
        let mv = mv.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_scale_multi_val(upma, mv) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_scale_val`.
    pub fn scale_val(self, val: Val) -> Result<UnionPwMultiAff, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let mut upma = upma;
        upma.do_not_free_on_drop();
        let upma = upma.ptr;
        let mut val = val;
        val.do_not_free_on_drop();
        let val = val.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_scale_val(upma, val) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_set_dim_name`.
    pub fn set_dim_name(self, type_: DimType, pos: u32, s: &str)
                        -> Result<UnionPwMultiAff, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let mut upma = upma;
        upma.do_not_free_on_drop();
        let upma = upma.ptr;
        let type_ = type_.to_i32();
        let s = CString::new(s).unwrap();
        let s = s.as_ptr();
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_set_dim_name(upma, type_, pos, s) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_sub`.
    pub fn sub(self, upma2: UnionPwMultiAff) -> Result<UnionPwMultiAff, LibISLError> {
        let upma1 = self;
        let isl_rs_ctx = upma1.get_ctx();
        let mut upma1 = upma1;
        upma1.do_not_free_on_drop();
        let upma1 = upma1.ptr;
        let mut upma2 = upma2;
        upma2.do_not_free_on_drop();
        let upma2 = upma2.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_sub(upma1, upma2) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_subtract_domain`.
    pub fn subtract_domain(self, uset: UnionSet) -> Result<UnionPwMultiAff, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let mut upma = upma;
        upma.do_not_free_on_drop();
        let upma = upma.ptr;
        let mut uset = uset;
        uset.do_not_free_on_drop();
        let uset = uset.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_subtract_domain(upma, uset) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_subtract_domain_space`.
    pub fn subtract_domain_space(self, space: Space) -> Result<UnionPwMultiAff, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let mut upma = upma;
        upma.do_not_free_on_drop();
        let upma = upma.ptr;
        let mut space = space;
        space.do_not_free_on_drop();
        let space = space.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_subtract_domain_space(upma, space) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_subtract_domain_union_set`.
    pub fn subtract_domain_union_set(self, uset: UnionSet) -> Result<UnionPwMultiAff, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let mut upma = upma;
        upma.do_not_free_on_drop();
        let upma = upma.ptr;
        let mut uset = uset;
        uset.do_not_free_on_drop();
        let uset = uset.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_subtract_domain_union_set(upma, uset) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_to_list`.
    pub fn to_list(self) -> Result<UnionPwMultiAffList, LibISLError> {
        let el = self;
        let isl_rs_ctx = el.get_ctx();
        let mut el = el;
        el.do_not_free_on_drop();
        let el = el.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_to_list(el) };
        let isl_rs_result = UnionPwMultiAffList { ptr: isl_rs_result,
                                                  should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_to_str`.
    pub fn to_str(&self) -> Result<&str, LibISLError> {
        let upma = self;
        let isl_rs_ctx = upma.get_ctx();
        let upma = upma.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_to_str(upma) };
        let isl_rs_result = unsafe { CStr::from_ptr(isl_rs_result) };
        let isl_rs_result = isl_rs_result.to_str().unwrap();
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Wraps `isl_union_pw_multi_aff_union_add`.
    pub fn union_add(self, upma2: UnionPwMultiAff) -> Result<UnionPwMultiAff, LibISLError> {
        let upma1 = self;
        let isl_rs_ctx = upma1.get_ctx();
        let mut upma1 = upma1;
        upma1.do_not_free_on_drop();
        let upma1 = upma1.ptr;
        let mut upma2 = upma2;
        upma2.do_not_free_on_drop();
        let upma2 = upma2.ptr;
        let isl_rs_result = unsafe { isl_union_pw_multi_aff_union_add(upma1, upma2) };
        let isl_rs_result = UnionPwMultiAff { ptr: isl_rs_result,
                                              should_free_on_drop: true };
        let err = isl_rs_ctx.last_error();
        if err != Error::None_ {
            return Err(LibISLError::new(err, isl_rs_ctx.last_error_msg()));
        }
        Ok(isl_rs_result)
    }

    /// Does not call isl_union_pw_multi_aff_free() on being dropped. (For
    /// internal use only.)
    pub fn do_not_free_on_drop(&mut self) {
        self.should_free_on_drop = false;
    }
}

impl Drop for UnionPwMultiAff {
    fn drop(&mut self) {
        if self.should_free_on_drop {
            unsafe {
                isl_union_pw_multi_aff_free(self.ptr);
            }
        }
    }
}
